import type { GeoPoint } from "./safety-engine";

export interface ReplayFrame {
  step: number;
  time: string;
  locationName: string;
  touristPosition: GeoPoint;
  responderPosition?: GeoPoint;
  riskScore: number;
  incidentStatus: string;
  aiRecommendation?: string;
  authorityDecision?: string;
  auditHash?: string;
  eventDescription: string;
}

export const deterministicReplayScenario: ReplayFrame[] = [
  {
    step: 1,
    time: "18:32:00",
    locationName: "Cubbon Park Entrance",
    touristPosition: { lat: 12.9757, lng: 77.6011 },
    riskScore: 28,
    incidentStatus: "NORMAL",
    eventDescription: "Tourist Aaron enters Cubbon Park safe corridor.",
  },
  {
    step: 2,
    time: "18:35:10",
    locationName: "Church Street Junction",
    touristPosition: { lat: 12.9742, lng: 77.6045 },
    riskScore: 48,
    incidentStatus: "RISK_INCREASING",
    eventDescription: "Zonal risk score increases to 48 (MEDIUM) due to high evening density.",
  },
  {
    step: 3,
    time: "18:37:40",
    locationName: "MG Road Approach",
    touristPosition: { lat: 12.9731, lng: 77.6078 },
    riskScore: 68,
    incidentStatus: "WARNING",
    aiRecommendation: "Pre-SOS Advisory: Accept Route B perimeter detour",
    eventDescription: "Pre-SOS warning generated by Edge Safety Engine.",
  },
  {
    step: 4,
    time: "18:39:15",
    locationName: "Brigade Road Transit",
    touristPosition: { lat: 12.9721, lng: 77.6095 },
    riskScore: 82,
    incidentStatus: "SOS_CREATED",
    eventDescription: "Tourist triggers Emergency SOS alert (Medical request).",
  },
  {
    step: 5,
    time: "18:40:02",
    locationName: "Brigade Road Transit",
    touristPosition: { lat: 12.9721, lng: 77.6095 },
    responderPosition: { lat: 12.9701, lng: 77.6025 },
    riskScore: 82,
    incidentStatus: "ACKNOWLEDGED",
    aiRecommendation: "Dispatch Unit R01 (Officer Rajesh Kumar)",
    authorityDecision: "APPROVED by Operator AUTH-OPERATOR-01",
    eventDescription: "Authority operator acknowledges SOS and approves Officer Rajesh dispatch.",
  },
  {
    step: 6,
    time: "18:44:20",
    locationName: "Brigade Road Transit",
    touristPosition: { lat: 12.9721, lng: 77.6095 },
    responderPosition: { lat: 12.9721, lng: 77.6095 },
    riskScore: 82,
    incidentStatus: "ON_SCENE",
    eventDescription: "First responder Unit R01 arrives on scene.",
  },
  {
    step: 7,
    time: "18:51:00",
    locationName: "Brigade Road Transit",
    touristPosition: { lat: 12.9721, lng: 77.6095 },
    responderPosition: { lat: 12.9721, lng: 77.6095 },
    riskScore: 30,
    incidentStatus: "RESOLVED",
    auditHash: "0x8f4a21b9c73e041d8e12f65a90b43c21",
    eventDescription: "Incident safely resolved & SHA-256 hash anchored to tamper-evident ledger.",
  },
];
