export interface StateEmergencyInfo {
  police: string;
  touristPolice: string;
  womenHelpline: string;
  ambulance: string;
  disasterManagement: string;
  highwayPatrol?: string;
  fireService: string;
}

export interface StateTouristZone {
  id: string;
  name: string;
  city: string;
  center: { lat: number; lng: number };
  radiusM: number;
  score: number;
  band: "SAFE" | "CAUTION" | "DANGER";
  incidentCount: number;
  factor: string;
  type: "CROWD" | "TERRAIN" | "ISOLATED" | "WILDLIFE" | "COASTAL" | "TRANSIT";
}

export interface StateSafePoint {
  id: string;
  name: string;
  type: "POLICE_STATION" | "HOSPITAL" | "TOURIST_KIOSK" | "HELP_DESK";
  address: string;
  phone: string;
  lat: number;
  lng: number;
}

export interface IndianStateData {
  id: string;
  name: string;
  code: string;
  capital: string;
  type: "STATE" | "UT";
  region: "North" | "South" | "East" | "West" | "Central" | "North-East" | "Islands";
  defaultLocation: { lat: number; lng: number };
  defaultLocationName: string;
  emergency: StateEmergencyInfo;
  popularDestinations: string[];
  riskZones: StateTouristZone[];
  safePoints: StateSafePoint[];
  advisories: string[];
  dosAndDonts: {
    dos: string[];
    donts: string[];
  };
  weatherAlert?: string;
  language: string;
}

export const allIndianStates: IndianStateData[] = [
  {
    id: "KA",
    name: "Karnataka",
    code: "KA",
    capital: "Bengaluru",
    type: "STATE",
    region: "South",
    defaultLocation: { lat: 12.9757, lng: 77.6068 },
    defaultLocationName: "MG Road, Bengaluru",
    language: "Kannada / English",
    emergency: {
      police: "112",
      touristPolice: "+91 80 2294 2222",
      womenHelpline: "1091",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Bengaluru", "Mysuru Palace", "Hampi (UNESCO)", "Coorg (Kodagu)", "Gokarna Beaches", "Chikkamagaluru", "Badami & Pattadakal"],
    riskZones: [
      { id: "KA-Z1", name: "MG Road Transit Corridor", city: "Bengaluru", center: { lat: 12.9753, lng: 77.6066 }, radiusM: 420, score: 74, band: "DANGER", incidentCount: 8, factor: "Elevated crowd and transit density after dark", type: "TRANSIT" },
      { id: "KA-Z2", name: "Church Street Junction", city: "Bengaluru", center: { lat: 12.9764, lng: 77.6015 }, radiusM: 310, score: 48, band: "CAUTION", incidentCount: 4, factor: "Crowd congestion during evening peak", type: "CROWD" },
      { id: "KA-Z3", name: "Cubbon Park Safe Point", city: "Bengaluru", center: { lat: 12.9767, lng: 77.5929 }, radiusM: 360, score: 20, band: "SAFE", incidentCount: 0, factor: "24x7 verified police kiosk presence", type: "TRANSIT" },
      { id: "KA-Z4", name: "Hampi Boulder Trails (Sunset point)", city: "Hampi", center: { lat: 15.3350, lng: 76.4600 }, radiusM: 500, score: 55, band: "CAUTION", incidentCount: 2, factor: "Uneven rock trails with low mobile coverage", type: "TERRAIN" },
    ],
    safePoints: [
      { id: "KA-S1", name: "Cubbon Park Tourist Police Station", type: "POLICE_STATION", address: "Kasturba Road, Bengaluru", phone: "+91 80 2294 2222", lat: 12.976, lng: 77.593 },
      { id: "KA-S2", name: "Bowring & Lady Curzon Hospital", type: "HOSPITAL", address: "Lady Curzon Rd, Tasker Town, Bengaluru", phone: "+91 80 2559 1362", lat: 12.981, lng: 77.604 },
      { id: "KA-S3", name: "Hampi Tourism Facilitation Centre", type: "TOURIST_KIOSK", address: "Near Virupaksha Temple, Hampi", phone: "+91 8394 241339", lat: 15.335, lng: 76.462 },
    ],
    advisories: ["Night travel on secluded ghat sections in Western Ghats should be avoided during heavy rains", "Official autorickshaw meters or app-based cabs recommended in Bengaluru"],
    dosAndDonts: {
      dos: ["Carry offline maps when trekking in Coorg and Western Ghats", "Respect dress codes inside ancient temple complexes in Hampi and Belur"],
      donts: ["Do not swim in unmonitored waterfalls or strong river rapids", "Avoid unofficial tour guides near monuments"],
    },
    weatherAlert: "Seasonal light rain in Bengaluru; clear skies in Hampi",
  },
  {
    id: "MH",
    name: "Maharashtra",
    code: "MH",
    capital: "Mumbai",
    type: "STATE",
    region: "West",
    defaultLocation: { lat: 18.9220, lng: 72.8347 },
    defaultLocationName: "Colaba & Gateway of India, Mumbai",
    language: "Marathi / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 22 2262 0826",
      womenHelpline: "103 / 1091",
      ambulance: "108",
      disasterManagement: "1916",
      highwayPatrol: "98224 98224",
      fireService: "101",
    },
    popularDestinations: ["Gateway of India & Marine Drive (Mumbai)", "Ajanta & Ellora Caves", "Lonavala & Khandala", "Mahabaleshwar", "Shirdi Sai Baba Temple", "Tarkarli Coastal Beach", "Pune Heritage Circuit"],
    riskZones: [
      { id: "MH-Z1", name: "Marine Drive Promenade Late Surge", city: "Mumbai", center: { lat: 18.9438, lng: 72.8231 }, radiusM: 350, score: 35, band: "SAFE", incidentCount: 1, factor: "Heavy public presence with high CCTV coverage", type: "CROWD" },
      { id: "MH-Z2", name: "Lonavala Tiger Point Cliff Edge", city: "Lonavala", center: { lat: 18.7320, lng: 73.3850 }, radiusM: 400, score: 68, band: "CAUTION", incidentCount: 5, factor: "Steep drops and dense fog during monsoon", type: "TERRAIN" },
      { id: "MH-Z3", name: "Dadar Transit Interchange", city: "Mumbai", center: { lat: 19.0178, lng: 72.8478 }, radiusM: 300, score: 72, band: "DANGER", incidentCount: 7, factor: "Extreme peak-hour crowd congestion and pickpocket risk", type: "TRANSIT" },
    ],
    safePoints: [
      { id: "MH-S1", name: "Colaba Tourist Police Outpost", type: "POLICE_STATION", address: "Near Gateway of India, Colaba, Mumbai", phone: "+91 22 2285 2885", lat: 18.922, lng: 72.834 },
      { id: "MH-S2", name: "GT Hospital / St. George Hospital", type: "HOSPITAL", address: "Fort, Mumbai", phone: "+91 22 2262 0241", lat: 18.939, lng: 72.835 },
    ],
    advisories: ["High tide warnings active during monsoon along Mumbai coastlines", "Use authorized MTDC registered guides at Ajanta & Ellora"],
    dosAndDonts: {
      dos: ["Keep emergency cash & digital payment options ready", "Check local suburban train rush hours before travelling with luggage"],
      donts: ["Never cross railway tracks or lean out of train doors", "Avoid venturing beyond safety barricades at waterfall viewpoints"],
    },
    weatherAlert: "Coastal breeze; pleasant evening temperatures",
  },
  {
    id: "DL",
    name: "Delhi (NCT)",
    code: "DL",
    capital: "New Delhi",
    type: "UT",
    region: "North",
    defaultLocation: { lat: 28.6139, lng: 77.2090 },
    defaultLocationName: "Connaught Place & India Gate, New Delhi",
    language: "Hindi / English / Punjabi",
    emergency: {
      police: "112",
      touristPolice: "+91 11 2346 9526",
      womenHelpline: "1091 / 181",
      ambulance: "102 / 108",
      disasterManagement: "1077",
      highwayPatrol: "1095",
      fireService: "101",
    },
    popularDestinations: ["India Gate & Kartavya Path", "Red Fort (Lal Qila)", "Qutub Minar", "Humayun's Tomb", "Connaught Place", "Akshardham Temple", "Chandni Chowk Heritage"],
    riskZones: [
      { id: "DL-Z1", name: "Chandni Chowk Narrow Alleyways", city: "Old Delhi", center: { lat: 28.6506, lng: 77.2303 }, radiusM: 380, score: 62, band: "CAUTION", incidentCount: 6, factor: "Heavy foot traffic, narrow passages, and touts", type: "CROWD" },
      { id: "DL-Z2", name: "New Delhi Railway Station Paharganj Exit", city: "New Delhi", center: { lat: 28.6430, lng: 77.2180 }, radiusM: 320, score: 76, band: "DANGER", incidentCount: 9, factor: "Unofficial travel agency touts and transit chaos", type: "TRANSIT" },
      { id: "DL-Z3", name: "Connaught Place Central Park Circle", city: "New Delhi", center: { lat: 28.6328, lng: 77.2197 }, radiusM: 400, score: 25, band: "SAFE", incidentCount: 1, factor: "Dedicated Delhi Tourist Police Booths & round-the-clock patrolling", type: "TRANSIT" },
    ],
    safePoints: [
      { id: "DL-S1", name: "Delhi Tourist Police Headquarters", type: "POLICE_STATION", address: "Janpath / Connaught Place, New Delhi", phone: "+91 11 2346 9526", lat: 28.631, lng: 77.219 },
      { id: "DL-S2", name: "All India Institute of Medical Sciences (AIIMS)", type: "HOSPITAL", address: "Ansari Nagar, New Delhi", phone: "+91 11 2658 8500", lat: 28.567, lng: 77.210 },
      { id: "DL-S3", name: "Indira Gandhi International Airport Police Kiosk", type: "HELP_DESK", address: "Terminal 3 Arrival Hall, New Delhi", phone: "+91 11 2565 6000", lat: 28.556, lng: 77.100 },
    ],
    advisories: ["Use prepaid taxi booths or verified ride-hailing apps at airport and railway stations", "Delhi Metro is the safest and fastest transport mode across the city"],
    dosAndDonts: {
      dos: ["Keep Delhi Tourist Police Helpline saved: +91 11 2346 9526", "Use the dedicated women-only coach at the front of Delhi Metro trains"],
      donts: ["Do not accept unsolicited hotel or tour booking offers from street strangers", "Avoid isolated parks after dark"],
    },
    weatherAlert: "Moderate air quality; metro networks running on full schedule",
  },
  {
    id: "RJ",
    name: "Rajasthan",
    code: "RJ",
    capital: "Jaipur",
    type: "STATE",
    region: "North",
    defaultLocation: { lat: 26.9124, lng: 75.7873 },
    defaultLocationName: "Hawa Mahal & Old Pink City, Jaipur",
    language: "Hindi / Rajasthani / English",
    emergency: {
      police: "112",
      touristPolice: "+91 141 238 5555",
      womenHelpline: "1090",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Jaipur (Amber Palace, Hawa Mahal)", "Udaipur (City Palace & Lake Pichola)", "Jodhpur (Mehrangarh Fort)", "Jaisalmer (Golden Fort & Thar Desert)", "Pushkar Holy Lake & Brahma Temple", "Ranthambore Tiger Reserve", "Mount Abu Hill Station"],
    riskZones: [
      { id: "RJ-Z1", name: "Sam Sand Dunes Desert Camp Area", city: "Jaisalmer", center: { lat: 26.8280, lng: 70.5100 }, radiusM: 800, score: 58, band: "CAUTION", incidentCount: 3, factor: "Unregulated desert safari operators and spotty network", type: "ISOLATED" },
      { id: "RJ-Z2", name: "Amber Fort Elephant Approach Corridor", city: "Jaipur", center: { lat: 26.9855, lng: 75.8513 }, radiusM: 350, score: 45, band: "CAUTION", incidentCount: 2, factor: "Aggressive gemstone and souvenir vendors", type: "CROWD" },
      { id: "RJ-Z3", name: "City Palace Heritage Safety Zone", city: "Udaipur", center: { lat: 24.5764, lng: 73.6835 }, radiusM: 400, score: 18, band: "SAFE", incidentCount: 0, factor: "Stationed tourist security guards and well-lit walkways", type: "CROWD" },
    ],
    safePoints: [
      { id: "RJ-S1", name: "Jaipur Tourist Police Station", type: "POLICE_STATION", address: "Near Hawa Mahal, Badi Chaupar, Jaipur", phone: "+91 141 238 5555", lat: 26.924, lng: 75.827 },
      { id: "RJ-S2", name: "SMS Hospital (Sawai Man Singh)", type: "HOSPITAL", address: "JLN Marg, Jaipur", phone: "+91 141 251 8222", lat: 26.896, lng: 75.815 },
    ],
    advisories: ["Always book desert camel/jeep safaris with RTDC or verified licensed operators", "Stay well-hydrated during daytime sightseeing"],
    dosAndDonts: {
      dos: ["Verify official monument entry tickets through the official department portal", "Dress conservatively when visiting holy sites in Pushkar and Ajmer"],
      donts: ["Never buy uncut gems or precious stones from unauthorized street dealers", "Do not wander deep into the Thar desert without a registered local guide"],
    },
    weatherAlert: "Warm sunny day; pleasant cool evening desert temperatures",
  },
  {
    id: "KL",
    name: "Kerala",
    code: "KL",
    capital: "Thiruvananthapuram",
    type: "STATE",
    region: "South",
    defaultLocation: { lat: 9.9312, lng: 76.2673 },
    defaultLocationName: "Fort Kochi & Mattancherry, Kochi",
    language: "Malayalam / English",
    emergency: {
      police: "112",
      touristPolice: "+91 484 221 5250",
      womenHelpline: "1091 / 181",
      ambulance: "108",
      disasterManagement: "1077",
      highwayPatrol: "98461 00100",
      fireService: "101",
    },
    popularDestinations: ["Alleppey (Alappuzha Backwaters)", "Munnar Tea Plantations", "Fort Kochi & Chinese Fishing Nets", "Wayanad Wildlife Sanctuary", "Varkala Cliff Beach", "Kovalam Beach", "Periyar Tiger Reserve (Thekkady)"],
    riskZones: [
      { id: "KL-Z1", name: "Varkala Cliff Edge Pathway", city: "Varkala", center: { lat: 8.7360, lng: 76.7020 }, radiusM: 350, score: 52, band: "CAUTION", incidentCount: 3, factor: "Eroding sandstone cliff edges and slippery paths", type: "COASTAL" },
      { id: "KL-Z2", name: "Munnar Top Station Mountain Ghat", city: "Munnar", center: { lat: 10.1250, lng: 77.2400 }, radiusM: 600, score: 65, band: "CAUTION", incidentCount: 4, factor: "Dense fog, steep hairpin curves, and sudden rainfall", type: "TERRAIN" },
      { id: "KL-Z3", name: "Fort Kochi Heritage Safe Zone", city: "Kochi", center: { lat: 9.9650, lng: 76.2420 }, radiusM: 450, score: 15, band: "SAFE", incidentCount: 0, factor: "Dedicated 24x7 Kerala Tourist Police Assistance Desk", type: "CROWD" },
    ],
    safePoints: [
      { id: "KL-S1", name: "Kerala Tourist Police Station", type: "POLICE_STATION", address: "Fort Kochi, Kochi", phone: "+91 484 221 5250", lat: 9.965, lng: 76.242 },
      { id: "KL-S2", name: "Ernakulam General Hospital", type: "HOSPITAL", address: "Hospital Rd, Marine Drive, Kochi", phone: "+91 484 236 0052", lat: 9.972, lng: 76.281 },
    ],
    advisories: ["Observe beach safety flags; avoid swimming during monsoon undertows", "Verify houseboat safety licenses with Kerala Tourism Department before booking"],
    dosAndDonts: {
      dos: ["Wear life jackets at all times on backwater boats and lake cruises", "Respect Ayurvedic treatment center credentials (look for Green/Olive Leaf certification)"],
      donts: ["Do not wander into deep forest trails in Wayanad without a forest department guide", "Do not sit on the unguarded cliff edges at Varkala"],
    },
    weatherAlert: "Pleasant coastal breeze; safe water conditions",
  },
  {
    id: "GA",
    name: "Goa",
    code: "GA",
    capital: "Panaji",
    type: "STATE",
    region: "West",
    defaultLocation: { lat: 15.4989, lng: 73.8278 },
    defaultLocationName: "Panaji Promenade & Miramar, Goa",
    language: "Konkani / English / Hindi",
    emergency: {
      police: "112",
      touristPolice: "+91 832 242 8333",
      womenHelpline: "1091",
      ambulance: "108",
      disasterManagement: "1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Calangute & Baga Beaches", "Anjuna & Vagator Cliffs", "Old Goa Churches (Basilica of Bom Jesus)", "Dudhsagar Waterfalls", "Palolem & Agonda Peaceful Beaches", "Panaji Latin Quarter (Fontainhas)", "Chapora Fort"],
    riskZones: [
      { id: "GA-Z1", name: "Baga-Calangute Nightlife Transit Strip", city: "North Goa", center: { lat: 15.5530, lng: 73.7550 }, radiusM: 600, score: 71, band: "DANGER", incidentCount: 9, factor: "Late night drunken driving incidents and tout scams", type: "TRANSIT" },
      { id: "GA-Z2", name: "Anjuna Rocky Beach Current Zone", city: "Anjuna", center: { lat: 15.5800, lng: 73.7420 }, radiusM: 400, score: 60, band: "CAUTION", incidentCount: 4, factor: "Submerged sharp rocks and sudden rip currents", type: "COASTAL" },
      { id: "GA-Z3", name: "Fontainhas Heritage Walk Zone", city: "Panaji", center: { lat: 15.4960, lng: 73.8320 }, radiusM: 350, score: 14, band: "SAFE", incidentCount: 0, factor: "Well-patrolled residential heritage zone with CCTV", type: "CROWD" },
    ],
    safePoints: [
      { id: "GA-S1", name: "Goa Tourist Police Assistance Centre", type: "POLICE_STATION", address: "Paryatan Bhavan, Panaji, Goa", phone: "+91 832 242 8333", lat: 15.498, lng: 73.827 },
      { id: "GA-S2", name: "Goa Medical College & Hospital (Bambolim)", type: "HOSPITAL", address: "NH 66, Bambolim, Goa", phone: "+91 832 245 8725", lat: 15.460, lng: 73.860 },
      { id: "GA-S3", name: "Drishti Marine Lifeguard Central Base", type: "HELP_DESK", address: "Calangute Beach Central Tower", phone: "+91 832 227 7010", lat: 15.543, lng: 73.755 },
    ],
    advisories: ["Always obey Drishti Lifeguard red warning flags on all beaches", "Wear ISI marked helmets when riding rented two-wheelers"],
    dosAndDonts: {
      dos: ["Rent vehicles only with official yellow-on-black commercial number plates", "Keep emergency lifeguard numbers handy"],
      donts: ["Never swim under the influence of alcohol or in red flag marked waters", "Do not buy contraband from unauthorized beach peddlers"],
    },
    weatherAlert: "Clear sunny beach weather; calm sea currents",
  },
  {
    id: "TN",
    name: "Tamil Nadu",
    code: "TN",
    capital: "Chennai",
    type: "STATE",
    region: "South",
    defaultLocation: { lat: 13.0827, lng: 80.2707 },
    defaultLocationName: "Marina Beach & Mylapore, Chennai",
    language: "Tamil / English",
    emergency: {
      police: "112",
      touristPolice: "+91 44 2846 1420",
      womenHelpline: "1091 / 181",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Chennai Marina & Mahabalipuram Shore Temples", "Madurai Meenakshi Amman Temple", "Ooty (Nilgiri Hills)", "Kodaikanal Lake", "Rameshwaram & Dhanushkodi", "Thanjavur Brihadisvara Temple", "Kanyakumari Southern Tip"],
    riskZones: [
      { id: "TN-Z1", name: "Dhanushkodi Ghost Town Sand Spit", city: "Rameshwaram", center: { lat: 9.1760, lng: 79.4180 }, radiusM: 700, score: 64, band: "CAUTION", incidentCount: 3, factor: "Unpredictable ocean tides, quicksand patches, and limited cellular signals", type: "COASTAL" },
      { id: "TN-Z2", name: "Nilgiri Mountain Hairpin Ghats", city: "Ooty", center: { lat: 11.4500, lng: 76.7800 }, radiusM: 600, score: 56, band: "CAUTION", incidentCount: 4, factor: "36 steep hairpin turns with heavy tourist bus traffic", type: "TERRAIN" },
      { id: "TN-Z3", name: "Mahabalipuram Monument Precinct", city: "Mahabalipuram", center: { lat: 12.6170, lng: 80.1920 }, radiusM: 500, score: 20, band: "SAFE", incidentCount: 0, factor: "ASI security & dedicated Tamil Nadu Tourist Police patrol", type: "CROWD" },
    ],
    safePoints: [
      { id: "TN-S1", name: "Tourist Police Wing - Marina", type: "POLICE_STATION", address: "Kamarajar Promenade, Chennai", phone: "+91 44 2846 1420", lat: 13.050, lng: 80.282 },
      { id: "TN-S2", name: "Rajiv Gandhi Government General Hospital", type: "HOSPITAL", address: "EVR Periyar Salai, Chennai", phone: "+91 44 2530 5000", lat: 13.080, lng: 80.278 },
    ],
    advisories: ["Strict eco-sensitive plastic ban in Nilgiris (Ooty) and Kodaikanal", "Follow temple dress codes strictly (traditional attire preferred)"],
    dosAndDonts: {
      dos: ["Book Ooty Nilgiri Mountain Railway tickets well in advance", "Stay within marked beach areas at Marina and Mahabalipuram"],
      donts: ["Do not drive past Dhanushkodi checkpost after 17:00 IST", "Do not feed wild elephants or monkeys along Nilgiri forest highways"],
    },
    weatherAlert: "Warm tropical sunshine; clear mountain visibility in Ooty",
  },
  {
    id: "UK",
    name: "Uttarakhand",
    code: "UK",
    capital: "Dehradun",
    type: "STATE",
    region: "North",
    defaultLocation: { lat: 30.0869, lng: 78.2676 },
    defaultLocationName: "Rishikesh Ghats & Laxman Jhula, Uttarakhand",
    language: "Hindi / Garhwali / Kumaoni / English",
    emergency: {
      police: "112",
      touristPolice: "+91 135 271 6201",
      womenHelpline: "1090",
      ambulance: "108",
      disasterManagement: "1070 / 1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Rishikesh (Yoga & White Water Rafting)", "Haridwar (Ganga Aarti)", "Mussoorie Queen of Hills", "Nainital Lake", "Jim Corbett National Park", "Char Dham (Badrinath, Kedarnath, Gangotri, Yamunotri)", "Auli Ski Resort & Valley of Flowers"],
    riskZones: [
      { id: "UK-Z1", name: "Kedarnath Trek Lincholi Landslide Zone", city: "Kedarnath", center: { lat: 30.6850, lng: 79.0550 }, radiusM: 900, score: 82, band: "DANGER", incidentCount: 11, factor: "High altitude sickness, sudden blizzards, and steep terrain", type: "TERRAIN" },
      { id: "UK-Z2", name: "Shivpuri Ganga Rapids Rafting Stretch", city: "Rishikesh", center: { lat: 30.1340, lng: 78.3880 }, radiusM: 600, score: 59, band: "CAUTION", incidentCount: 5, factor: "Grade 4 rapids requiring certified river guides and life jackets", type: "TERRAIN" },
      { id: "UK-Z3", name: "Triveni Ghat Evening Safety Zone", city: "Rishikesh", center: { lat: 30.1030, lng: 78.2970 }, radiusM: 400, score: 18, band: "SAFE", incidentCount: 0, factor: "SDRF life-guards, CCTV coverage, and flood barrier lighting", type: "CROWD" },
    ],
    safePoints: [
      { id: "UK-S1", name: "Uttarakhand SDRF Tourist Safety Base", type: "POLICE_STATION", address: "Muni Ki Reti, Rishikesh", phone: "+91 135 243 0112", lat: 30.119, lng: 78.308 },
      { id: "UK-S2", name: "AIIMS Rishikesh Hospital & Trauma Centre", type: "HOSPITAL", address: "Virbhadra Road, Rishikesh", phone: "+91 135 246 2929", lat: 30.076, lng: 78.288 },
    ],
    advisories: ["Mandatory biometric registration required for Char Dham Yatra pilgrims", "Check road status via Uttarakhand Disaster App before high-altitude driving"],
    dosAndDonts: {
      dos: ["Acclimatize properly and carry portable oxygen canisters during high-altitude treks", "Hire only licensed rafting operators registered with Uttarakhand Tourism"],
      donts: ["Never attempt off-trail hiking without a registered mountain guide", "Do not drive on ghat roads during heavy monsoon rainfall"],
    },
    weatherAlert: "Clear mountain skies; cold nights in higher altitude zones",
  },
  {
    id: "HP",
    name: "Himachal Pradesh",
    code: "HP",
    capital: "Shimla",
    type: "STATE",
    region: "North",
    defaultLocation: { lat: 32.2396, lng: 77.1887 },
    defaultLocationName: "Mall Road & Old Manali, Himachal",
    language: "Hindi / Pahari / English",
    emergency: {
      police: "112",
      touristPolice: "+91 177 262 7755",
      womenHelpline: "1091",
      ambulance: "108",
      disasterManagement: "1070 / 1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Manali & Solang Valley", "Shimla Mall Road & Kufri", "Dharamshala & McLeod Ganj", "Spiti Valley & Kaza", "Kasol & Parvati Valley", "Dalhousie & Khajjiar", "Atal Tunnel & Rohtang Pass"],
    riskZones: [
      { id: "HP-Z1", name: "Rohtang Pass & Kunzum Pass High Snow Zone", city: "Manali/Spiti", center: { lat: 32.3710, lng: 77.2460 }, radiusM: 1000, score: 79, band: "DANGER", incidentCount: 8, factor: "Sub-zero ice conditions, sudden blizzards, and oxygen depletion", type: "TERRAIN" },
      { id: "HP-Z2", name: "Parvati Valley Isolated Forest Trails", city: "Kasol", center: { lat: 32.0100, lng: 77.3150 }, radiusM: 800, score: 67, band: "CAUTION", incidentCount: 6, factor: "Treacherous river trails, steep gorges, and no cellular reception", type: "ISOLATED" },
      { id: "HP-Z3", name: "Shimla Mall Road Pedestrian Safe Zone", city: "Shimla", center: { lat: 31.1048, lng: 77.1734 }, radiusM: 500, score: 12, band: "SAFE", incidentCount: 0, factor: "Vehicle-free pedestrian promenade with 24x7 police patrolling", type: "CROWD" },
    ],
    safePoints: [
      { id: "HP-S1", name: "Himachal Police Tourist Help Desk", type: "POLICE_STATION", address: "The Ridge / Mall Road, Shimla", phone: "+91 177 262 7755", lat: 31.105, lng: 77.174 },
      { id: "HP-S2", name: "Civil Hospital Manali", type: "HOSPITAL", address: "Model Town, Manali", phone: "+91 1902 252 347", lat: 32.242, lng: 77.189 },
    ],
    advisories: ["Rohtang Pass requires advance permit from the administration", "Never trek alone in Parvati Valley; always register with local police outpost"],
    dosAndDonts: {
      dos: ["Check Atal Tunnel clearance status during winter months", "Keep warm thermal clothing and sturdy grip footwear ready"],
      donts: ["Do not approach rushing waters of Beas or Parvati rivers for selfies", "Avoid driving rented sedans on rugged Spiti gravel tracks"],
    },
    weatherAlert: "Scenic weather in valleys; snow clearance active on high passes",
  },
  {
    id: "LA",
    name: "Ladakh",
    code: "LA",
    capital: "Leh",
    type: "UT",
    region: "North",
    defaultLocation: { lat: 34.1526, lng: 77.5771 },
    defaultLocationName: "Leh Market & Shanti Stupa, Ladakh",
    language: "Ladakhi / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 1982 258 880",
      womenHelpline: "1091",
      ambulance: "108 / 102",
      disasterManagement: "1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Pangong Tso Lake", "Nubra Valley & Hunder Sand Dunes", "Khardung La Pass (5,359m)", "Magnetic Hill & Indus Zanskar Confluence", "Shanti Stupa & Leh Palace", "Tso Moriri High Altitude Lake", "Hemis & Thiksey Monasteries"],
    riskZones: [
      { id: "LA-Z1", name: "Khardung La / Chang La Passes", city: "Ladakh", center: { lat: 34.2780, lng: 77.6040 }, radiusM: 1200, score: 85, band: "DANGER", incidentCount: 12, factor: "Severe Acute Mountain Sickness (AMS), freezing winds, and altitude 17,500ft+", type: "TERRAIN" },
      { id: "LA-Z2", name: "Pangong Tso Remote Border Area", city: "Pangong", center: { lat: 33.7590, lng: 78.6670 }, radiusM: 1500, score: 62, band: "CAUTION", incidentCount: 4, factor: "Near zero nighttime temperatures and no mobile coverage", type: "ISOLATED" },
      { id: "LA-Z3", name: "Leh Main Bazaar Tourist Safe Hub", city: "Leh", center: { lat: 34.1640, lng: 77.5840 }, radiusM: 400, score: 16, band: "SAFE", incidentCount: 0, factor: "Tourist Police HQ, oxygen parlours, and medical first-responders", type: "CROWD" },
    ],
    safePoints: [
      { id: "LA-S1", name: "Ladakh Tourist Police Help Desk", type: "POLICE_STATION", address: "Main Market, Leh", phone: "+91 1982 258 880", lat: 34.164, lng: 77.584 },
      { id: "LA-S2", name: "SNM Hospital Leh (Equipped with Hyperbaric Oxygen)", type: "HOSPITAL", address: "Hospital Road, Leh", phone: "+91 1982 252 012", lat: 34.159, lng: 77.581 },
    ],
    advisories: ["Mandatory 48-hour complete rest in Leh required upon arrival by flight for acclimatization", "Inner Line Permit (ILP) required for Nubra, Pangong, and Changthang"],
    dosAndDonts: {
      dos: ["Drink 3–4 litres of water daily to prevent AMS; carry Diamox if prescribed", "Respect local Ladakhi Buddhist heritage and wildlife (Snow Leopards, Black-necked cranes)"],
      donts: ["Never sleep at Khardung La pass top (limit halt to maximum 15 minutes)", "Do not off-road on pristine lake shores of Pangong or Tso Moriri"],
    },
    weatherAlert: "High UV index during day; sub-zero overnight temperatures",
  },
  {
    id: "JK",
    name: "Jammu and Kashmir",
    code: "JK",
    capital: "Srinagar (Summer) / Jammu (Winter)",
    type: "UT",
    region: "North",
    defaultLocation: { lat: 34.0837, lng: 74.7973 },
    defaultLocationName: "Dal Lake Boulevard & Lal Chowk, Srinagar",
    language: "Kashmiri / Urdu / Dogri / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 194 247 7052",
      womenHelpline: "1091",
      ambulance: "108 / 102",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Dal Lake Shikara & Houseboats (Srinagar)", "Gulmarg Gondola & Ski Slopes", "Pahalgam Valley & Betaab Valley", "Sonamarg Meadow of Gold", "Shri Mata Vaishno Devi Shrine (Katra)", "Mughal Gardens (Shalimar & Nishat)", "Doodhpathri"],
    riskZones: [
      { id: "JK-Z1", name: "Gulmarg Apharwat Peak Phase 2 Slopes", city: "Gulmarg", center: { lat: 34.0300, lng: 74.3400 }, radiusM: 900, score: 75, band: "DANGER", incidentCount: 6, factor: "Avalanche risk and extreme sub-zero winds above 13,000ft", type: "TERRAIN" },
      { id: "JK-Z2", name: "Zojila Pass Highway Corridor", city: "Sonamarg", center: { lat: 34.2800, lng: 75.1700 }, radiusM: 1000, score: 70, band: "CAUTION", incidentCount: 5, factor: "Unpaved narrow cliff road prone to rockfalls", type: "TERRAIN" },
      { id: "JK-Z3", name: "Dal Lake Boulevard Tourist Hub", city: "Srinagar", center: { lat: 34.0880, lng: 74.8350 }, radiusM: 500, score: 20, band: "SAFE", incidentCount: 1, factor: "J&K Tourist Police Station, Shikara rescue boats, and high security", type: "CROWD" },
    ],
    safePoints: [
      { id: "JK-S1", name: "Srinagar Tourist Police Station", type: "POLICE_STATION", address: "TRC Ground, Srinagar", phone: "+91 194 247 7052", lat: 34.072, lng: 74.821 },
      { id: "JK-S2", name: "SKIMS Hospital (Sher-i-Kashmir Institute)", type: "HOSPITAL", address: "Soura, Srinagar", phone: "+91 194 240 1013", lat: 34.135, lng: 74.801 },
    ],
    advisories: ["Book official Gulmarg Gondola tickets online only via the J&K Cable Car Corporation portal", "Prepaid mobile SIM cards from outside J&K do not work (only postpaid works)"],
    dosAndDonts: {
      dos: ["Purchase or activate a local postpaid/eSIM on arrival if needed", "Verify government-approved rates for pony rides and Shikaras"],
      donts: ["Do not wander past marked border advisory signposts in frontier zones", "Avoid buying saffron without official GI-tag certification"],
    },
    weatherAlert: "Chilly crisp mountain breeze; Gondola operating smoothly",
  },
  {
    id: "WB",
    name: "West Bengal",
    code: "WB",
    capital: "Kolkata",
    type: "STATE",
    region: "East",
    defaultLocation: { lat: 22.5726, lng: 88.3639 },
    defaultLocationName: "Park Street & Victoria Memorial, Kolkata",
    language: "Bengali / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 33 2214 5000",
      womenHelpline: "1091",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Victoria Memorial & Howrah Bridge (Kolkata)", "Darjeeling Himalayan Toy Train & Tiger Hill", "Sundarbans National Park (Mangroves & Royal Bengal Tigers)", "Kalimpong & Kurseong", "Digha & Mandarmani Coastal Beaches", "Shantiniketan (Tagore's Ashram)", "Murshidabad Historic Palaces"],
    riskZones: [
      { id: "WB-Z1", name: "Sundarbans Deep Creek Delta", city: "Sundarbans", center: { lat: 21.9497, lng: 88.8997 }, radiusM: 1500, score: 76, band: "DANGER", incidentCount: 5, factor: "Tidal surges, dense mangrove swamps, and wild tiger zones", type: "WILDLIFE" },
      { id: "WB-Z2", name: "Tiger Hill Early Dawn Ascent Road", city: "Darjeeling", center: { lat: 27.0000, lng: 88.2600 }, radiusM: 600, score: 50, band: "CAUTION", incidentCount: 3, factor: "Heavy pre-dawn tourist vehicle jams and zero-visibility fog", type: "TERRAIN" },
      { id: "WB-Z3", name: "Victoria Memorial & Maidan Safe Zone", city: "Kolkata", center: { lat: 22.5448, lng: 88.3426 }, radiusM: 500, score: 18, band: "SAFE", incidentCount: 0, factor: "Well-lit heritage gardens with round-the-clock Kolkata Police patrols", type: "CROWD" },
    ],
    safePoints: [
      { id: "WB-S1", name: "Kolkata Police Tourist Assistance Wing", type: "POLICE_STATION", address: "Lalbazar / Maidan, Kolkata", phone: "+91 33 2214 5000", lat: 22.573, lng: 88.351 },
      { id: "WB-S2", name: "SSKM Hospital & Trauma Centre", type: "HOSPITAL", address: "AJC Bose Road, Kolkata", phone: "+91 33 2223 1589", lat: 22.539, lng: 88.343 },
    ],
    advisories: ["Enter the Sundarbans only with forest department registered motor launches and licensed guides", "Yellow Ambassador taxis and Metro provide reliable transit across Kolkata"],
    dosAndDonts: {
      dos: ["Taste world-famous authentic Darjeeling tea from certified tea estates", "Experience the iconic tram and metro network in Kolkata"],
      donts: ["Never step off authorized tourist boats in Sundarban creeks", "Avoid unmetered street taxis outside Howrah and Sealdah stations"],
    },
    weatherAlert: "Pleasant river breeze; clear sunrise views over Mt. Kanchenjunga",
  },
  {
    id: "UP",
    name: "Uttar Pradesh",
    code: "UP",
    capital: "Lucknow",
    type: "STATE",
    region: "North",
    defaultLocation: { lat: 27.1751, lng: 78.0421 },
    defaultLocationName: "Taj Mahal & Fatehpur Sikri, Agra",
    language: "Hindi / Urdu / English",
    emergency: {
      police: "112",
      touristPolice: "+91 562 242 1204",
      womenHelpline: "1090 / 181",
      ambulance: "108 / 102",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Taj Mahal & Agra Fort (Agra)", "Varanasi Ghats & Kashi Vishwanath", "Lucknow (Bara Imambara & Awadhi Heritage)", "Mathura & Vrindavan Krishna Janmabhoomi", "Ayodhya Ram Mandir Complex", "Prayagraj Triveni Sangam", "Sarnath Buddhist Stupa"],
    riskZones: [
      { id: "UP-Z1", name: "Taj Mahal East/West Gate Vendor Corridor", city: "Agra", center: { lat: 27.1730, lng: 78.0400 }, radiusM: 350, score: 62, band: "CAUTION", incidentCount: 7, factor: "Persistent marble souvenir touts and fake guide rackets", type: "CROWD" },
      { id: "UP-Z2", name: "Dashashwamedh & Manikarnika Ghat Steps", city: "Varanasi", center: { lat: 25.3080, lng: 83.0110 }, radiusM: 400, score: 66, band: "CAUTION", incidentCount: 6, factor: "Extremely crowded slippery stone steps and swift river currents", type: "CROWD" },
      { id: "UP-Z3", name: "Taj Mahal Inner Protected Precinct", city: "Agra", center: { lat: 27.1751, lng: 78.0421 }, radiusM: 500, score: 12, band: "SAFE", incidentCount: 0, factor: "High-security CISF perimeter and UP Tourist Police Station", type: "CROWD" },
    ],
    safePoints: [
      { id: "UP-S1", name: "Agra Tourist Police Station", type: "POLICE_STATION", address: "Near Taj Mahal East Gate, Agra", phone: "+91 562 242 1204", lat: 27.174, lng: 78.045 },
      { id: "UP-S2", name: "Varanasi Tourist Police Assistance Kiosk", type: "POLICE_STATION", address: "Dashashwamedh Ghat, Varanasi", phone: "+91 542 250 8031", lat: 25.308, lng: 83.011 },
      { id: "UP-S3", name: "Sir Sunderlal Hospital (BHU Varanasi)", type: "HOSPITAL", address: "BHU Campus, Varanasi", phone: "+91 542 230 7500", lat: 25.275, lng: 82.999 },
    ],
    advisories: ["Taj Mahal is closed for tourists on Fridays; purchase tickets online via the ASI portal", "Only hire guides with official Ministry of Tourism photo ID badges"],
    dosAndDonts: {
      dos: ["Book morning boat rides at Varanasi through registered boatmen associations", "Wear life jackets on all Ganga boat tours"],
      donts: ["Never buy costly marble inlay work without official authenticity receipt", "Avoid photography at cremation ghats in Varanasi out of respect"],
    },
    weatherAlert: "Clear sunny day; excellent visibility for Taj Mahal sunrise",
  },
  {
    id: "GJ",
    name: "Gujarat",
    code: "GJ",
    capital: "Gandhinagar",
    type: "STATE",
    region: "West",
    defaultLocation: { lat: 21.8380, lng: 73.7191 },
    defaultLocationName: "Statue of Unity, Kevadia, Gujarat",
    language: "Gujarati / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 79 2325 0000",
      womenHelpline: "181 (Abhayam)",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Statue of Unity (World's Tallest Statue)", "Rann of Kutch (White Desert & Rann Utsav)", "Gir National Park (Asiatic Lions)", "Somnath & Dwarka Temples", "Ahmedabad UNESCO Heritage City & Sabarmati Ashram", "Rani Ki Vav Stepwell (Patan)", "Sun Temple Modhera"],
    riskZones: [
      { id: "GJ-Z1", name: "Great Rann of Kutch Salt Flats Remote Area", city: "Kutch", center: { lat: 23.8340, lng: 69.8300 }, radiusM: 1200, score: 68, band: "CAUTION", incidentCount: 4, factor: "Disorienting salt terrain, extreme temperature variation, and zero network", type: "ISOLATED" },
      { id: "GJ-Z2", name: "Gir Forest Buffer Zone", city: "Sasan Gir", center: { lat: 21.1240, lng: 70.8240 }, radiusM: 900, score: 70, band: "CAUTION", incidentCount: 3, factor: "Wild Asiatic lion territory; strict permits mandatory", type: "WILDLIFE" },
      { id: "GJ-Z3", name: "Statue of Unity Visitor Campus", city: "Kevadia", center: { lat: 21.8380, lng: 73.7191 }, radiusM: 800, score: 14, band: "SAFE", incidentCount: 0, factor: "Ultra-modern e-bus transit, CCTV monitoring, and dedicated tourist safety staff", type: "TRANSIT" },
    ],
    safePoints: [
      { id: "GJ-S1", name: "Statue of Unity Tourism Control Room", type: "TOURIST_KIOSK", address: "Kevadia Colony, Ekta Nagar", phone: "+91 1800 233 6600", lat: 21.838, lng: 73.719 },
      { id: "GJ-S2", name: "Civil Hospital Ahmedabad", type: "HOSPITAL", address: "Asarwa, Ahmedabad", phone: "+91 79 2268 3721", lat: 23.052, lng: 72.597 },
    ],
    advisories: ["Inner line permit required for visiting Dhordo/Kutch border zone (can be obtained online)", "Gujarat is a dry state; foreign and domestic tourists can obtain liquor permits legally if required"],
    dosAndDonts: {
      dos: ["Book Gir lion safaris months in advance via the official forest department portal", "Experience the White Rann during full moon nights for the best view"],
      donts: ["Never attempt walking deep into the salt desert without a local guide", "Do not tease or feed animals during Gir open jeep safaris"],
    },
    weatherAlert: "Pleasant sunny weather; cool desert breeze in Kutch",
  },
  {
    id: "TS",
    name: "Telangana",
    code: "TS",
    capital: "Hyderabad",
    type: "STATE",
    region: "South",
    defaultLocation: { lat: 17.3616, lng: 78.4747 },
    defaultLocationName: "Charminar & Golconda Fort, Hyderabad",
    language: "Telugu / Urdu / Hindi / English",
    emergency: {
      police: "112 / 100",
      touristPolice: "+91 40 2345 0112",
      womenHelpline: "1091 / SHE Teams",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Charminar & Laad Bazaar (Hyderabad)", "Golconda Fort & Sound/Light Show", "Ramoji Film City", "Hussain Sagar & Buddha Statue", "Chowmahalla Palace", "Warangal Fort & Thousand Pillar Temple", "Nagarjuna Sagar Dam"],
    riskZones: [
      { id: "TS-Z1", name: "Laad Bazaar & Charminar Old City", city: "Hyderabad", center: { lat: 17.3610, lng: 78.4730 }, radiusM: 350, score: 58, band: "CAUTION", incidentCount: 5, factor: "Narrow bustling bangle lanes, dense traffic, and street pickpockets", type: "CROWD" },
      { id: "TS-Z2", name: "Golconda Fort Steep Upper Ramparts", city: "Hyderabad", center: { lat: 17.3830, lng: 78.4010 }, radiusM: 400, score: 46, band: "CAUTION", incidentCount: 2, factor: "Steep granite stairs with uneven footing", type: "TERRAIN" },
      { id: "TS-Z3", name: "Necklace Road & Hussain Sagar Walkway", city: "Hyderabad", center: { lat: 17.4240, lng: 78.4680 }, radiusM: 450, score: 18, band: "SAFE", incidentCount: 0, factor: "Dedicated Hyderabad Police SHE Teams & Lake Police patrol boats", type: "CROWD" },
    ],
    safePoints: [
      { id: "TS-S1", name: "Hyderabad Lake Police & Tourist Desk", type: "POLICE_STATION", address: "Necklace Road, Hussain Sagar", phone: "+91 40 2785 2418", lat: 17.424, lng: 78.468 },
      { id: "TS-S2", name: "Osmania General Hospital", type: "HOSPITAL", address: "Afzal Gunj, Hyderabad", phone: "+91 40 2460 0146", lat: 17.375, lng: 78.477 },
    ],
    advisories: ["Hyderabad SHE Teams provide active 24x7 women safety support in all crowded hubs", "Use Hyderabad Metro for fast travel between IT corridor and Old City"],
    dosAndDonts: {
      dos: ["Taste authentic Hyderabadi Biryani from renowned heritage kitchens", "Keep the SHE Team emergency contact handy: WhatsApp +91 94906 16555"],
      donts: ["Avoid unauthorized gem or pearl sellers on the streets", "Do not climb unguarded outer ruin walls at Golconda Fort"],
    },
    weatherAlert: "Warm afternoon; pleasant breeze around Hussain Sagar lake",
  },
  {
    id: "AP",
    name: "Andhra Pradesh",
    code: "AP",
    capital: "Amaravati",
    type: "STATE",
    region: "South",
    defaultLocation: { lat: 13.6288, lng: 79.4192 },
    defaultLocationName: "Tirupati & Tirumala Hills, Andhra Pradesh",
    language: "Telugu / English",
    emergency: {
      police: "112",
      touristPolice: "+91 877 228 9112",
      womenHelpline: "1091 / Disha SOS",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Tirupati Balaji Temple (Tirumala)", "Visakhapatnam (RK Beach & Rishikonda)", "Araku Valley & Borra Caves", "Lepakshi Hanging Pillar Temple", "Srisailam Mallikarjuna Jyotirlinga", "Gandikota Grand Canyon of India", "Belum Caves"],
    riskZones: [
      { id: "AP-Z1", name: "Tirumala Ghat Road Hairpin Curves", city: "Tirupati", center: { lat: 13.6600, lng: 79.3800 }, radiusM: 700, score: 54, band: "CAUTION", incidentCount: 4, factor: "Strict speed monitoring and sharp descending mountain bends", type: "TERRAIN" },
      { id: "AP-Z2", name: "Gandikota Gorge Cliff Viewpoint", city: "Kadapa", center: { lat: 14.8150, lng: 78.2860 }, radiusM: 500, score: 65, band: "CAUTION", incidentCount: 3, factor: "Unfenced 300ft gorge drops; extreme caution required on boulders", type: "TERRAIN" },
      { id: "AP-Z3", name: "Tirumala Temple Main Queue Complex", city: "Tirumala", center: { lat: 13.6830, lng: 79.3470 }, radiusM: 600, score: 15, band: "SAFE", incidentCount: 0, factor: "TTD Vigilance and Security forces with thousands of integrated CCTV cameras", type: "CROWD" },
    ],
    safePoints: [
      { id: "AP-S1", name: "TTD Vigilance & Police Security HQ", type: "POLICE_STATION", address: "Tirumala, Tirupati", phone: "+91 877 227 7777", lat: 13.683, lng: 79.347 },
      { id: "AP-S2", name: "SVIMS Super Specialty Hospital", type: "HOSPITAL", address: "Alipiri Road, Tirupati", phone: "+91 877 228 7777", lat: 13.639, lng: 79.403 },
    ],
    advisories: ["Book Tirumala Darshan tickets strictly via the official TTD website (tirupatibalaji.ap.gov.in)", "Download Andhra Pradesh Disha App for one-touch SOS dispatch"],
    dosAndDonts: {
      dos: ["Adhere to traditional dress code (Dhoti/Kurta for men, Saree/Chudidar for women) at Tirumala", "Follow lifeguards' instructions at Rishikonda Blue Flag Beach in Vizag"],
      donts: ["Do not buy fake VIP darshan passes from unauthorized agents in Tirupati", "Do not stand on edge rocks at Gandikota canyon for photos"],
    },
    weatherAlert: "Sunny and clear; pleasant weather in Araku valley",
  },
  {
    id: "OD",
    name: "Odisha",
    code: "OD",
    capital: "Bhubaneswar",
    type: "STATE",
    region: "East",
    defaultLocation: { lat: 19.8135, lng: 85.8312 },
    defaultLocationName: "Puri Jagannath Temple & Golden Beach, Odisha",
    language: "Odia / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 6752 222 050",
      womenHelpline: "1091 / 181",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Puri Jagannath Temple & Golden Beach (Blue Flag)", "Konark Sun Temple (UNESCO)", "Bhubaneswar Temple City & Lingaraj", "Chilika Lake (Irrawaddy Dolphins)", "Simlipal National Park & Biosphere", "Udayagiri & Khandagiri Caves", "Dhauli Shanti Stupa"],
    riskZones: [
      { id: "OD-Z1", name: "Puri Swargadwar Beach Strong Undertow", city: "Puri", center: { lat: 19.7940, lng: 85.8180 }, radiusM: 500, score: 63, band: "CAUTION", incidentCount: 5, factor: "Strong undertow currents during high tide; swim only in marked areas", type: "COASTAL" },
      { id: "OD-Z2", name: "Puri Golden Beach (Blue Flag Zone)", city: "Puri", center: { lat: 19.8020, lng: 85.8320 }, radiusM: 400, score: 14, band: "SAFE", incidentCount: 0, factor: "International Blue Flag certified beach with trained life-guards and CCTV", type: "COASTAL" },
    ],
    safePoints: [
      { id: "OD-S1", name: "Puri Tourist Police Station", type: "POLICE_STATION", address: "Sea Beach Road, Puri", phone: "+91 6752 222 050", lat: 19.800, lng: 85.828 },
      { id: "OD-S2", name: "District Headquarters Hospital Puri", type: "HOSPITAL", address: "Grand Road, Puri", phone: "+91 6752 222 032", lat: 19.812, lng: 85.825 },
    ],
    advisories: ["Non-Hindus are not permitted inside the sanctum of Puri Jagannath Temple, but can view from the Raghunandan Library roof", "Take certified Odisha Tourism OTDC boat tours at Chilika lake"],
    dosAndDonts: {
      dos: ["Visit Konark Sun Temple early morning for incredible lighting and lesser crowd", "Taste authentic Odisha Chhena Poda dessert"],
      donts: ["Never swim deep into the sea past red flags at Puri beach", "Do not engage with unregistered Panda priests offering VIP temple entries"],
    },
    weatherAlert: "Gentle coastal breeze; clear skies at Konark",
  },
  {
    id: "AS",
    name: "Assam",
    code: "AS",
    capital: "Dispur (Guwahati)",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 26.1445, lng: 91.7362 },
    defaultLocationName: "Kamakhya Temple & Brahmaputra Riverfront, Guwahati",
    language: "Assamese / Bengali / Bodo / English / Hindi",
    emergency: {
      police: "112",
      touristPolice: "+91 361 254 0225",
      womenHelpline: "1091 / 181",
      ambulance: "108",
      disasterManagement: "1070 / 1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Kaziranga National Park (One-horned Rhinos)", "Kamakhya Devi Temple (Guwahati)", "Majuli River Island (World's Largest)", "Manas National Park (UNESCO)", "Sivasagar Ahom Dynasty Monuments", "Hoollongapar Gibbon Sanctuary", "Haflong Hill Station"],
    riskZones: [
      { id: "AS-Z1", name: "Kaziranga NH 715 Animal Crossing Corridor", city: "Kaziranga", center: { lat: 26.5775, lng: 93.1711 }, radiusM: 1000, score: 68, band: "CAUTION", incidentCount: 4, factor: "Strict 40 km/h speed sensor zones; wild rhinos and elephants crossing", type: "WILDLIFE" },
      { id: "AS-Z2", name: "Kamakhya Nilachal Hill Approach Steps", city: "Guwahati", center: { lat: 26.1664, lng: 91.7056 }, radiusM: 400, score: 48, band: "CAUTION", incidentCount: 3, factor: "Heavy pilgrim queues and slippery stone steps", type: "CROWD" },
      { id: "AS-Z3", name: "Guwahati Brahmaputra Riverfront Promenade", city: "Guwahati", center: { lat: 26.1880, lng: 91.7450 }, radiusM: 450, score: 18, band: "SAFE", incidentCount: 0, factor: "River police patrols and modern riverwalk lighting", type: "CROWD" },
    ],
    safePoints: [
      { id: "AS-S1", name: "Guwahati Tourist Police Outpost", type: "POLICE_STATION", address: "Station Road / Paltan Bazaar, Guwahati", phone: "+91 361 254 0225", lat: 26.181, lng: 71.748 },
      { id: "AS-S2", name: "Gauhati Medical College & Hospital (GMCH)", type: "HOSPITAL", address: "Bhangagarh, Guwahati", phone: "+91 361 252 9457", lat: 26.155, lng: 91.772 },
    ],
    advisories: ["Kaziranga National Park remains closed during monsoon (May to October) due to floods", "Speed cameras strictly enforce 40 km/h on Kaziranga highway corridors to protect wildlife"],
    dosAndDonts: {
      dos: ["Book elephant and jeep safaris at Kaziranga via official portal (kaziranga.assam.gov.in)", "Taste authentic Assam orthodox black tea and visit Majuli Satras (monasteries)"],
      donts: ["Never step out of open safari jeeps in Kaziranga or Manas", "Do not photograph defense installations near river bridges"],
    },
    weatherAlert: "Pleasant river breeze; optimal visibility for wildlife safaris",
  },
  {
    id: "SK",
    name: "Sikkim",
    code: "SK",
    capital: "Gangtok",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 27.3389, lng: 88.6065 },
    defaultLocationName: "MG Marg Promenade, Gangtok, Sikkim",
    language: "Nepali / Bhutia / Lepcha / English / Hindi",
    emergency: {
      police: "112",
      touristPolice: "+91 3592 202 022",
      womenHelpline: "1091",
      ambulance: "108 / 102",
      disasterManagement: "1070 / 1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Gangtok MG Marg & Rumtek Monastery", "Tsomgo (Changu) Lake & Nathu La Pass", "Gurudongmar High Altitude Lake (17,800ft)", "Yumthang Valley of Flowers & Lachung", "Pelling & Skywalk with Kanchenjunga views", "Ravangla Buddha Park", "Zuluk Silk Route Hairpins"],
    riskZones: [
      { id: "SK-Z1", name: "Nathu La & Tsomgo Lake Frozen Road", city: "East Sikkim", center: { lat: 27.3870, lng: 88.8310 }, radiusM: 1000, score: 78, band: "DANGER", incidentCount: 6, factor: "Heavy sub-zero snowfall, icy roads, and low oxygen at 14,000ft", type: "TERRAIN" },
      { id: "SK-Z2", name: "Gurudongmar Lake Extreme Altitude Track", city: "North Sikkim", center: { lat: 28.0250, lng: 88.7120 }, radiusM: 1200, score: 86, band: "DANGER", incidentCount: 8, factor: "Severe altitude sickness risk, no mobile network, and extreme cold", type: "ISOLATED" },
      { id: "SK-Z3", name: "MG Marg Gangtok Safe Promenade", city: "Gangtok", center: { lat: 27.3310, lng: 88.6130 }, radiusM: 400, score: 10, band: "SAFE", incidentCount: 0, factor: "India's cleanest pedestrian shopping boulevard with zero vehicles and 24x7 police kiosks", type: "CROWD" },
    ],
    safePoints: [
      { id: "SK-S1", name: "Sikkim Tourist Information & Police Desk", type: "POLICE_STATION", address: "MG Marg, Gangtok", phone: "+91 3592 202 022", lat: 27.331, lng: 88.613 },
      { id: "SK-S2", name: "STNM Hospital Gangtok", type: "HOSPITAL", address: "Sochakgang, Gangtok", phone: "+91 3592 201 100", lat: 27.320, lng: 88.605 },
    ],
    advisories: ["Special Protected Area Permit (PAP) required for Nathu La, Tsomgo, and North Sikkim", "Sikkim is a 100% organic state; plastic water bottles are strictly prohibited in North Sikkim"],
    dosAndDonts: {
      dos: ["Carry reusable water bottles and warm multiple layers of clothing", "Consult a doctor before traveling with young children or elderly to Gurudongmar Lake"],
      donts: ["Do not litter; strict fines enforced across the entire state", "Do not photograph international border posts at Nathu La"],
    },
    weatherAlert: "Clear sunny day in Gangtok; winter permit checks active for Nathu La",
  },
  {
    id: "MP",
    name: "Madhya Pradesh",
    code: "MP",
    capital: "Bhopal",
    type: "STATE",
    region: "Central",
    defaultLocation: { lat: 23.2599, lng: 77.4126 },
    defaultLocationName: "Bhopal Upper Lake & Sanchi Stupa, MP",
    language: "Hindi / Bundelkhandi / English",
    emergency: {
      police: "112 / 100",
      touristPolice: "+91 755 277 8383",
      womenHelpline: "1090",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Khajuraho Temples (UNESCO)", "Bandhavgarh & Kanha Tiger Reserves", "Sanchi Stupa (Buddhist World Heritage)", "Gwalior Fort & Scindia Palace", "Ujjain Mahakaleshwar Jyotirlinga", "Bhedaghat Marble Rocks (Jabalpur)", "Pachmarhi Hill Station & Orchha Forts"],
    riskZones: [
      { id: "MP-Z1", name: "Bandhavgarh Tala Safari Deep Forest", city: "Bandhavgarh", center: { lat: 23.6930, lng: 81.0280 }, radiusM: 900, score: 72, band: "CAUTION", incidentCount: 3, factor: "Highest density of wild Royal Bengal Tigers in India", type: "WILDLIFE" },
      { id: "MP-Z2", name: "Khajuraho Monument Complex Safety Perimeter", city: "Khajuraho", center: { lat: 24.8520, lng: 79.9190 }, radiusM: 450, score: 18, band: "SAFE", incidentCount: 0, factor: "MP Tourism Police Station and verified guide association", type: "CROWD" },
    ],
    safePoints: [
      { id: "MP-S1", name: "Khajuraho Tourist Police Desk", type: "POLICE_STATION", address: "Opposite Western Group of Temples, Khajuraho", phone: "+91 7686 274 048", lat: 24.852, lng: 79.919 },
      { id: "MP-S2", name: "AIIMS Bhopal Trauma Centre", type: "HOSPITAL", address: "Saket Nagar, Bhopal", phone: "+91 755 267 2355", lat: 23.208, lng: 77.460 },
    ],
    advisories: ["Book MP tiger safaris 120 days in advance on the MP forest portal", "Bhedaghat boat rides are closed during monsoon months"],
    dosAndDonts: {
      dos: ["Experience the evening Bhasma Aarti at Ujjain Mahakal (online booking required)", "Hire authorized ASI badge guides at Khajuraho and Sanchi"],
      donts: ["Never wear bright clothing during wildlife safaris (wear earth tones/khaki)", "Do not wander outside resort boundaries after dusk in tiger reserves"],
    },
    weatherAlert: "Pleasant sunshine across heritage monuments; clear safari trails",
  },
  {
    id: "PB",
    name: "Punjab",
    code: "PB",
    capital: "Chandigarh",
    type: "STATE",
    region: "North",
    defaultLocation: { lat: 31.6200, lng: 74.8765 },
    defaultLocationName: "Golden Temple (Harmandir Sahib), Amritsar",
    language: "Punjabi / Hindi / English",
    emergency: {
      police: "112",
      touristPolice: "+91 183 255 7670",
      womenHelpline: "181 / 1091",
      ambulance: "108",
      disasterManagement: "1070",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Sri Harmandir Sahib (Golden Temple)", "Attari-Wagah Border Ceremony", "Jallianwala Bagh Memorial", "Partition Museum Amritsar", "Qila Mubarak (Patiala)", "Virasat-e-Khalsa (Anandpur Sahib)", "Rock Garden & Sukhna Lake (Chandigarh)"],
    riskZones: [
      { id: "PB-Z1", name: "Attari-Wagah Border Public Surge Arena", city: "Amritsar", center: { lat: 31.6040, lng: 74.5710 }, radiusM: 500, score: 55, band: "CAUTION", incidentCount: 4, factor: "Massive spectator crowds during evening retreat ceremony", type: "CROWD" },
      { id: "PB-Z2", name: "Golden Temple Heritage Precinct", city: "Amritsar", center: { lat: 31.6200, lng: 74.8765 }, radiusM: 600, score: 10, band: "SAFE", incidentCount: 0, factor: "24x7 peaceful volunteer Sevadar security and community emergency aid", type: "CROWD" },
    ],
    safePoints: [
      { id: "PB-S1", name: "Amritsar Tourist Police Facilitation Centre", type: "POLICE_STATION", address: "Near Golden Temple Heritage Walk, Amritsar", phone: "+91 183 255 7670", lat: 31.621, lng: 74.877 },
      { id: "PB-S2", name: "Guru Nanak Dev Hospital", type: "HOSPITAL", address: "Majitha Road, Amritsar", phone: "+91 183 257 6820", lat: 31.649, lng: 74.875 },
    ],
    advisories: ["Head coverings and bare feet (after washing in holy footbaths) are mandatory inside the Golden Temple complex", "Arrive at Wagah Border by 15:30 IST to secure good seating"],
    dosAndDonts: {
      dos: ["Partake in the Guru ka Langar (free community kitchen) at Golden Temple", "Cover your head with a scarf before stepping into the sacred complex"],
      donts: ["Alcohol, tobacco, and non-vegetarian food are strictly prohibited around Golden Temple", "Do not carry large bags or power banks to the Wagah border stadium"],
    },
    weatherAlert: "Clear sunny weather; pleasant evening atmosphere around the Sarovar",
  },
  {
    id: "AN",
    name: "Andaman and Nicobar Islands",
    code: "AN",
    capital: "Port Blair",
    type: "UT",
    region: "Islands",
    defaultLocation: { lat: 11.6234, lng: 92.7265 },
    defaultLocationName: "Cellular Jail & Radhanagar Beach, Havelock",
    language: "Bengali / Hindi / Tamil / English",
    emergency: {
      police: "112 / 100",
      touristPolice: "+91 3192 232 100",
      womenHelpline: "1091",
      ambulance: "102 / 108",
      disasterManagement: "1070 / 1077",
      highwayPatrol: "1033",
      fireService: "101",
    },
    popularDestinations: ["Radhanagar Beach (Havelock Island / Swaraj Dweep)", "Cellular Jail (Port Blair)", "Elephant Beach (Snorkeling & Coral Reefs)", "Neil Island (Shaheed Dweep Natural Bridge)", "Ross Island (Netaji Subhash Chandra Bose Dweep)", "Baratang Island (Limestone Caves)", "Chidiya Tapu Sunset Point"],
    riskZones: [
      { id: "AN-Z1", name: "Baratang Tribal Reserve Buffer Corridor", city: "Baratang", center: { lat: 12.1300, lng: 92.7500 }, radiusM: 1000, score: 72, band: "CAUTION", incidentCount: 2, factor: "Strict protected Jarawa tribal reserve; convoy travel only", type: "ISOLATED" },
      { id: "AN-Z2", name: "Radhanagar Beach (Blue Flag)", city: "Havelock", center: { lat: 11.9830, lng: 92.9500 }, radiusM: 600, score: 14, band: "SAFE", incidentCount: 0, factor: "Dedicated coastal lifeguards and crocodile exclusion nets", type: "COASTAL" },
    ],
    safePoints: [
      { id: "AN-S1", name: "Port Blair Tourist Police Hub", type: "POLICE_STATION", address: "Aberdeen Bazaar, Port Blair", phone: "+91 3192 232 100", lat: 11.666, lng: 92.742 },
      { id: "AN-S2", name: "G.B. Pant Hospital", type: "HOSPITAL", address: "Atlanta Point, Port Blair", phone: "+91 3192 233 473", lat: 11.668, lng: 92.746 },
    ],
    advisories: ["Photography of or interaction with indigenous Jarawa and Sentinelese tribes is strictly illegal under severe penalty", "Book inter-island government ferries or private catamarans (Makruzz/Green Ocean) in advance"],
    dosAndDonts: {
      dos: ["Wear life jackets on all speedboats and scuba diving excursions", "Carry cash as island ATMs may occasionally experience network downtime"],
      donts: ["Do not collect corals, shells, or sea creatures from beaches or reefs (illegal)", "Never swim at beaches with crocodile warning signboards"],
    },
    weatherAlert: "Tropical sunshine; calm turquoise waters ideal for scuba & snorkeling",
  },
  // All remaining States and UTs to complete the full 36 Indian States & UTs
  {
    id: "BR",
    name: "Bihar",
    code: "BR",
    capital: "Patna",
    type: "STATE",
    region: "East",
    defaultLocation: { lat: 24.6961, lng: 84.9869 },
    defaultLocationName: "Mahabodhi Temple & Bodh Gaya, Bihar",
    language: "Hindi / Maithili / Bhojpuri / Magahi / English",
    emergency: { police: "112", touristPolice: "+91 631 220 0777", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Bodh Gaya (Mahabodhi Temple UNESCO)", "Nalanda Ancient University Ruins", "Rajgir (Vishwa Shanti Stupa & Ropeway)", "Patna Sahib Gurudwara", "Valmiki National Park", "Vaishali Ashoka Pillar"],
    riskZones: [
      { id: "BR-Z1", name: "Bodh Gaya Temple Precinct Safe Zone", city: "Bodh Gaya", center: { lat: 24.6961, lng: 84.9869 }, radiusM: 450, score: 15, band: "SAFE", incidentCount: 0, factor: "International pilgrim security and 24x7 tourist assistance", type: "CROWD" },
    ],
    safePoints: [{ id: "BR-S1", name: "Bodh Gaya Tourist Police Desk", type: "POLICE_STATION", address: "Mahabodhi Temple Road, Bodh Gaya", phone: "+91 631 220 0777", lat: 24.696, lng: 84.986 }],
    advisories: ["Respect meditation silence inside Mahabodhi temple sanctum"],
    dosAndDonts: { dos: ["Explore the Nalanda archaeological museum"], donts: ["Do not use unauthorized private transit in remote rural tracks"] },
    weatherAlert: "Clear sunny skies; peaceful pilgrimage conditions",
  },
  {
    id: "CH",
    name: "Chandigarh",
    code: "CH",
    capital: "Chandigarh",
    type: "UT",
    region: "North",
    defaultLocation: { lat: 30.7333, lng: 76.7794 },
    defaultLocationName: "Sector 17 & Rock Garden, Chandigarh",
    language: "Punjabi / Hindi / English",
    emergency: { police: "112", touristPolice: "+91 172 274 0400", womenHelpline: "1091", ambulance: "108", disasterManagement: "1077", fireService: "101" },
    popularDestinations: ["Nek Chand's Rock Garden", "Sukhna Lake Promenade", "Zakir Hussain Rose Garden", "Sector 17 Plaza", "Capitol Complex (UNESCO Heritage)"],
    riskZones: [{ id: "CH-Z1", name: "Sukhna Lake Safe Promenade", city: "Chandigarh", center: { lat: 30.7420, lng: 76.8180 }, radiusM: 500, score: 10, band: "SAFE", incidentCount: 0, factor: "Strict traffic enforcement and dedicated bicycle/pedestrian lanes", type: "CROWD" }],
    safePoints: [{ id: "CH-S1", name: "Chandigarh Tourist Police Kiosk", type: "POLICE_STATION", address: "Sector 17 Plaza, Chandigarh", phone: "+91 172 274 0400", lat: 30.735, lng: 76.780 }],
    advisories: ["Strict traffic rules and speed cameras operate across all city sectors"],
    dosAndDonts: { dos: ["Use marked pedestrian crossings (zebra crossings)"], donts: ["Do not honk; Chandigarh strictly enforces silence zones"] },
    weatherAlert: "Pleasant cool breeze around Sukhna Lake",
  },
  {
    id: "CT",
    name: "Chhattisgarh",
    code: "CT",
    capital: "Raipur",
    type: "STATE",
    region: "Central",
    defaultLocation: { lat: 19.2017, lng: 81.7584 },
    defaultLocationName: "Chitrakote Falls (Niagara of India), Bastar",
    language: "Chhattisgarhi / Hindi / Gondi",
    emergency: { police: "112", touristPolice: "+91 771 405 7777", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Chitrakote & Tirathgarh Waterfalls (Bastar)", "Kanger Valley National Park & Kutumsar Caves", "Barnawapara Wildlife Sanctuary", "Sirpur Heritage Buddhist Complex", "Mainpat Hill Station (Mini Tibet)"],
    riskZones: [{ id: "CT-Z1", name: "Chitrakote Falls Viewpoint Safe Area", city: "Jagdalpur", center: { lat: 19.2017, lng: 81.7584 }, radiusM: 400, score: 22, band: "SAFE", incidentCount: 0, factor: "Resort security and certified boatmen", type: "COASTAL" }],
    safePoints: [{ id: "CT-S1", name: "Bastar Tourist Police Help Desk", type: "POLICE_STATION", address: "Jagdalpur, Bastar", phone: "+91 7782 222 100", lat: 19.070, lng: 82.030 }],
    advisories: ["Stick to primary highway routes and official eco-tourism circuits in Bastar"],
    dosAndDonts: { dos: ["Buy authentic Dokra brass and Bell Metal handicrafts directly from tribal artisans"], donts: ["Do not wander into deep unguided forest interiors"] },
    weatherAlert: "Majestic waterfalls with full spray",
  },
  {
    id: "JH",
    name: "Jharkhand",
    code: "JH",
    capital: "Ranchi",
    type: "STATE",
    region: "East",
    defaultLocation: { lat: 23.3441, lng: 85.3096 },
    defaultLocationName: "Hundru Falls & Tagore Hill, Ranchi",
    language: "Hindi / Santhali / Nagpuri",
    emergency: { police: "112", touristPolice: "+91 651 240 0950", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Hundru & Jonha Waterfalls", "Betla National Park & Palamu Tiger Reserve", "Deoghar Baba Baidyanath Jyotirlinga", "Parasnath Jain Tirth (Shikharji)", "Netarhat Queen of Chotanagpur"],
    riskZones: [{ id: "JH-Z1", name: "Baidyanath Dham Temple Safe Corridor", city: "Deoghar", center: { lat: 24.4920, lng: 86.7000 }, radiusM: 400, score: 24, band: "SAFE", incidentCount: 0, factor: "Continuous police surveillance and crowd control barricades", type: "CROWD" }],
    safePoints: [{ id: "JH-S1", name: "Ranchi Tourist Information Centre", type: "HELP_DESK", address: "Ranchi Railway Station, Ranchi", phone: "+91 651 240 0950", lat: 23.350, lng: 85.330 }],
    advisories: ["Avoid descending to the base of slippery waterfall rocks during heavy monsoon"],
    dosAndDonts: { dos: ["Experience sunset at Netarhat Magnolia Point"], donts: ["Do not swim in unmonitored waterfall deep plunge pools"] },
    weatherAlert: "Pleasant hill climate in Netarhat",
  },
  {
    id: "HR",
    name: "Haryana",
    code: "HR",
    capital: "Chandigarh",
    type: "STATE",
    region: "North",
    defaultLocation: { lat: 28.4595, lng: 77.0266 },
    defaultLocationName: "Cyber City & Sultanpur Bird Sanctuary, Gurugram",
    language: "Haryanvi / Hindi / Punjabi / English",
    emergency: { police: "112", touristPolice: "+91 124 238 6000", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Sultanpur National Park & Bird Sanctuary", "Kurukshetra (Brahma Sarovar & Mahabharata Sites)", "Pinjore Gardens (Yadavindra Gardens)", "Morni Hills & Tikkar Taal", "Damdama Lake Eco Retreat"],
    riskZones: [{ id: "HR-Z1", name: "Cyber Hub Gurugram Safe Zone", city: "Gurugram", center: { lat: 28.4950, lng: 77.0880 }, radiusM: 450, score: 14, band: "SAFE", incidentCount: 0, factor: "Private & state police security and 24x7 camera network", type: "CROWD" }],
    safePoints: [{ id: "HR-S1", name: "Gurugram Police Assistance Centre", type: "POLICE_STATION", address: "Cyber City, DLF Phase 2, Gurugram", phone: "+91 124 238 6000", lat: 28.495, lng: 77.088 }],
    advisories: ["Book birdwatching permits early for Sultanpur during winter migratory season"],
    dosAndDonts: { dos: ["Use Rapid Metro for transit in Gurugram"], donts: ["Avoid speeding on expressways; high-speed radar cameras in effect"] },
    weatherAlert: "Clear sunny weather across northern plains",
  },
  {
    id: "AR",
    name: "Arunachal Pradesh",
    code: "AR",
    capital: "Itanagar",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 27.5861, lng: 91.8653 },
    defaultLocationName: "Tawang Monastery & Sela Pass, Arunachal",
    language: "English / Monpa / Nyishi / Hindi",
    emergency: { police: "112", touristPolice: "+91 360 221 2233", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Tawang Monastery (India's Largest)", "Sela Pass & Sela Lake (13,700ft)", "Ziro Valley (Apatani Culture & Music Fest)", "Namdapha National Park", "Madhuri Lake (Sangetsar Tso)", "Mechuka Valley"],
    riskZones: [{ id: "AR-Z1", name: "Sela Pass High Altitude Stretch", city: "Tawang", center: { lat: 27.5050, lng: 92.1000 }, radiusM: 900, score: 76, band: "DANGER", incidentCount: 5, factor: "Black ice, heavy snowfall, and steep mountain passes", type: "TERRAIN" }],
    safePoints: [{ id: "AR-S1", name: "Tawang Tourist Police Post", type: "POLICE_STATION", address: "Main Market, Tawang", phone: "+91 3794 222 221", lat: 27.586, lng: 91.865 }],
    advisories: ["Inner Line Permit (ILP) for Indian citizens and PAP for foreign nationals is strictly mandatory"],
    dosAndDonts: { dos: ["Acclimatize in Dirang before crossing Sela Pass to Tawang"], donts: ["Do not travel without valid ILP documentation"] },
    weatherAlert: "Snow cover on high passes; roads maintained by BRO",
  },
  {
    id: "ML",
    name: "Meghalaya",
    code: "ML",
    capital: "Shillong",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 25.5788, lng: 91.8933 },
    defaultLocationName: "Police Bazar, Shillong & Cherrapunji",
    language: "Khasi / Garo / Pnar / English",
    emergency: { police: "112", touristPolice: "+91 364 222 2214", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Cherrapunji (Sohra) & Nohkalikai Falls", "Double Decker Living Root Bridge (Nongriat)", "Dawki Umngot Crystal Clear River", "Mawlynnong (Asia's Cleanest Village)", "Shillong Peak & Elephant Falls", "Laitlum Canyons", "Krang Suri Waterfalls"],
    riskZones: [{ id: "ML-Z1", name: "Nongriat 3,000 Step Root Bridge Trek", city: "Cherrapunji", center: { lat: 25.2500, lng: 91.6800 }, radiusM: 700, score: 58, band: "CAUTION", incidentCount: 4, factor: "Strenuous steep 3,000 stairs with high humidity", type: "TERRAIN" }],
    safePoints: [{ id: "ML-S1", name: "Shillong Tourist Information Centre", type: "HELP_DESK", address: "Police Bazar, Shillong", phone: "+91 364 222 2214", lat: 25.578, lng: 91.893 }],
    advisories: ["Carry raincoat and dry bags when visiting Cherrapunji and Mawsynram"],
    dosAndDonts: { dos: ["Experience boating on crystal clear waters of Dawki during winter"], donts: ["Never litter in Mawlynnong or protected sacred groves"] },
    weatherAlert: "Pleasant misty hills; crystal clear river visibility in Dawki",
  },
  {
    id: "MN",
    name: "Manipur",
    code: "MN",
    capital: "Imphal",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 24.8170, lng: 93.9368 },
    defaultLocationName: "Loktak Lake & Kangla Fort, Imphal",
    language: "Meiteilon (Manipuri) / English",
    emergency: { police: "112", touristPolice: "+91 385 245 0000", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Loktak Lake & Floating Phumdis", "Keibul Lamjao (World's Only Floating National Park / Sangai Deer)", "Kangla Fort Heritage", "Ima Keithel (All-Women Market)", "INA Memorial Moirang"],
    riskZones: [{ id: "MN-Z1", name: "Ima Keithel Safe Market Hub", city: "Imphal", center: { lat: 24.8050, lng: 93.9380 }, radiusM: 350, score: 18, band: "SAFE", incidentCount: 0, factor: "Centuries-old all-women vendor market with active community vigilance", type: "CROWD" }],
    safePoints: [{ id: "MN-S1", name: "Imphal Tourist Information Bureau", type: "HELP_DESK", address: "Kangla Fort Road, Imphal", phone: "+91 385 245 0000", lat: 24.817, lng: 93.936 }],
    advisories: ["Inner Line Permit (ILP) required for visiting Manipur; apply online prior to arrival"],
    dosAndDonts: { dos: ["Witness the unique floating circular phumdis of Loktak lake"], donts: ["Avoid night road travel between remote hill districts"] },
    weatherAlert: "Pleasant lake breeze around Loktak",
  },
  {
    id: "MZ",
    name: "Mizoram",
    code: "MZ",
    capital: "Aizawl",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 23.7271, lng: 92.7176 },
    defaultLocationName: "Aizawl City & Reiek Peak, Mizoram",
    language: "Mizo / English",
    emergency: { police: "112", touristPolice: "+91 389 233 4440", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Reiek Heritage Village & Peak", "Vantawng Falls", "Solomon's Temple Aizawl", "Tamdil Serene Lake", "Phawngpui Blue Mountain"],
    riskZones: [{ id: "MZ-Z1", name: "Aizawl Model Traffic Safe Zone", city: "Aizawl", center: { lat: 23.7271, lng: 92.7176 }, radiusM: 400, score: 12, band: "SAFE", incidentCount: 0, factor: "World-famous no-honking and disciplined single-lane hill traffic", type: "TRANSIT" }],
    safePoints: [{ id: "MZ-S1", name: "Aizawl Tourist Information Office", type: "HELP_DESK", address: "Chaltlang, Aizawl", phone: "+91 389 233 4440", lat: 23.740, lng: 92.720 }],
    advisories: ["ILP is required for all visitors entering Mizoram"],
    dosAndDonts: { dos: ["Observe the peaceful no-honking driving culture"], donts: ["Never throw trash along pristine scenic hill ridges"] },
    weatherAlert: "Clear mountain air and cool breeze",
  },
  {
    id: "NL",
    name: "Nagaland",
    code: "NL",
    capital: "Kohima",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 25.6751, lng: 94.1086 },
    defaultLocationName: "Kohima & Dzukou Valley, Nagaland",
    language: "English / Nagamese / Tenyidie",
    emergency: { police: "112", touristPolice: "+91 370 229 0140", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Hornbill Festival (Kisama Heritage Village)", "Dzukou Valley Trek (Valley of Flowers)", "Kohima WWII War Cemetery", "Khonoma Green Village (India's First Green Village)", "Mokokchung Ao Tribal Culture"],
    riskZones: [{ id: "NL-Z1", name: "Dzukou Valley Alpine Trek", city: "Kohima", center: { lat: 25.5500, lng: 94.0500 }, radiusM: 800, score: 56, band: "CAUTION", incidentCount: 3, factor: "Chilly alpine weather, sudden fog, and steep natural trails", type: "TERRAIN" }],
    safePoints: [{ id: "NL-S1", name: "Nagaland Tourist Police Post", type: "POLICE_STATION", address: "Main Town, Kohima", phone: "+91 370 229 0140", lat: 25.675, lng: 94.108 }],
    advisories: ["Mandatory ILP for domestic tourists (can be issued online)"],
    dosAndDonts: { dos: ["Visit the Hornbill Festival in December for Naga indigenous music & art"], donts: ["Do not light campfires in the fragile eco-zone of Dzukou valley"] },
    weatherAlert: "Cool mountain climate with fresh alpine scents",
  },
  {
    id: "TR",
    name: "Tripura",
    code: "TR",
    capital: "Agartala",
    type: "STATE",
    region: "North-East",
    defaultLocation: { lat: 23.8315, lng: 91.2868 },
    defaultLocationName: "Ujjayanta Palace & Neermahal, Tripura",
    language: "Bengali / Kokborok / English",
    emergency: { police: "112", touristPolice: "+91 381 232 5930", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Ujjayanta Palace (Agartala)", "Neermahal Water Palace (Rudrasagar Lake)", "Unakoti Rock Carvings (Angkor Wat of the North-East)", "Tripura Sundari Temple (Udaipur)", "Jampui Hills (Orange & Orchids)"],
    riskZones: [{ id: "TR-Z1", name: "Ujjayanta Palace Heritage Safe Zone", city: "Agartala", center: { lat: 23.8315, lng: 91.2868 }, radiusM: 400, score: 14, band: "SAFE", incidentCount: 0, factor: "State museum complex with high security and lighting", type: "CROWD" }],
    safePoints: [{ id: "TR-S1", name: "Tripura Tourism Office", type: "HELP_DESK", address: "Palace Compound, Agartala", phone: "+91 381 232 5930", lat: 23.831, lng: 91.286 }],
    advisories: ["Unakoti requires moderate walking down stone steps; wear comfortable shoes"],
    dosAndDonts: { dos: ["Take a motorboat ride to Neermahal Water Palace"], donts: ["Do not touch or climb on ancient stone bas-reliefs at Unakoti"] },
    weatherAlert: "Warm sunny afternoon; pleasant lakeside weather",
  },
  {
    id: "DD",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    code: "DD",
    capital: "Daman",
    type: "UT",
    region: "West",
    defaultLocation: { lat: 20.3974, lng: 72.8328 },
    defaultLocationName: "Daman Fort & Devka Beach, Daman",
    language: "Gujarati / Hindi / Portuguese / English",
    emergency: { police: "112", touristPolice: "+91 260 225 5100", womenHelpline: "1091", ambulance: "108", disasterManagement: "1077", fireService: "101" },
    popularDestinations: ["Moti Daman Fort & Lighthouse", "Devka & Jampore Beaches", "Diu Fort & Naida Caves", "St. Paul's Church Diu", "Silvassa Lion Safari & Dudhani Lake"],
    riskZones: [{ id: "DD-Z1", name: "Jampore Beach Water Sports Safe Area", city: "Daman", center: { lat: 20.3600, lng: 72.8400 }, radiusM: 400, score: 16, band: "SAFE", incidentCount: 0, factor: "Black sand calm waters with stationed coast guards", type: "COASTAL" }],
    safePoints: [{ id: "DD-S1", name: "Daman Tourist Police Post", type: "POLICE_STATION", address: "Moti Daman, Daman", phone: "+91 260 225 5100", lat: 20.397, lng: 72.832 }],
    advisories: ["Naida Caves have natural rock pathways; carry flashlights in late afternoon"],
    dosAndDonts: { dos: ["Explore Portuguese colonial architecture in Diu"], donts: ["Never swim near rocky cliffs outside marked beach zones"] },
    weatherAlert: "Calm sunny coastal weather",
  },
  {
    id: "LD",
    name: "Lakshadweep",
    code: "LD",
    capital: "Kavaratti",
    type: "UT",
    region: "Islands",
    defaultLocation: { lat: 10.5667, lng: 72.6417 },
    defaultLocationName: "Agatti Island & Bangaram Atoll, Lakshadweep",
    language: "Malayalam / Jeseri / Mahal / English",
    emergency: { police: "112", touristPolice: "+91 4896 262 258", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["Bangaram Atoll (Pristine Coral Lagoon)", "Agatti Island Beach & Runway", "Kadmat Island Water Sports Hub", "Minicoy Island Lighthouse & Culture", "Kavaratti Marine Aquarium"],
    riskZones: [{ id: "LD-Z1", name: "Bangaram Lagoon Water Safe Sanctuary", city: "Bangaram", center: { lat: 10.9400, lng: 72.2900 }, radiusM: 800, score: 10, band: "SAFE", incidentCount: 0, factor: "Protected coral lagoon with master PADI dive rescue team", type: "COASTAL" }],
    safePoints: [{ id: "LD-S1", name: "Agatti Island Police Post", type: "POLICE_STATION", address: "Agatti, Lakshadweep", phone: "+91 4894 242 222", lat: 10.850, lng: 72.180 }],
    advisories: ["Entry permit is mandatory for all non-residents (obtain via SPORTS tourism portal)"],
    dosAndDonts: { dos: ["Experience scuba diving in turquoise lagoons with 30-meter visibility"], donts: ["Strictly zero removal of corals or sea-shells from the atolls"] },
    weatherAlert: "Crystal clear turquoise water; calm tropical lagoon",
  },
  {
    id: "PY",
    name: "Puducherry",
    code: "PY",
    capital: "Puducherry",
    type: "UT",
    region: "South",
    defaultLocation: { lat: 11.9338, lng: 79.8297 },
    defaultLocationName: "French Quarter (White Town) & Promenade, Puducherry",
    language: "Tamil / French / English",
    emergency: { police: "112", touristPolice: "+91 413 233 4000", womenHelpline: "1091", ambulance: "108", disasterManagement: "1070", fireService: "101" },
    popularDestinations: ["White Town (French Colony) & Promenade Beach", "Auroville & Matrimandir Golden Globe", "Paradise Beach (Chunnambar Boat House)", "Aurobindo Ashram", "Serenity Beach (Surfing)", "Botanical Gardens"],
    riskZones: [{ id: "PY-Z1", name: "White Town Promenade Pedestrian Zone", city: "Puducherry", center: { lat: 11.9338, lng: 79.8297 }, radiusM: 500, score: 12, band: "SAFE", incidentCount: 0, factor: "Vehicle-free ocean promenade between 18:00 to 07:30 daily", type: "CROWD" }],
    safePoints: [{ id: "PY-S1", name: "Puducherry Tourist Police Station", type: "POLICE_STATION", address: "Goubert Avenue / Beach Road, Puducherry", phone: "+91 413 233 4000", lat: 11.933, lng: 79.833 }],
    advisories: ["Matrimandir viewing point requires free advance booking pass at Auroville Visitor Centre"],
    dosAndDonts: { dos: ["Rent a vintage bicycle to explore the yellow French Quarter villas"], donts: ["Do not climb over rock seawall boulders during high tide at Promenade"] },
    weatherAlert: "Cool sea breeze along the French promenade",
  },
];

export function getStateById(idOrCode: string): IndianStateData | undefined {
  const upper = idOrCode.toUpperCase().trim();
  return allIndianStates.find(
    (s) => s.id.toUpperCase() === upper || s.code.toUpperCase() === upper || s.name.toLowerCase() === idOrCode.toLowerCase(),
  );
}

export const totalTerritoriesCount = allIndianStates.length; // 36 States and UTs!
