import type { WeatherStation, WeatherObservation } from "./weather-types";

export const initialWeatherStations: WeatherStation[] = [
  // Karnataka Stations
  {
    stationId: "AWS-KA-101",
    name: "Bengaluru Central AWS",
    stateId: "KA",
    district: "Bengaluru Urban",
    location: { lat: 12.9716, lng: 77.5946 },
    elevationM: 920,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.98,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "RAIN", "VISIBILITY"],
  },
  {
    stationId: "AWS-KA-102",
    name: "Cubbon Park Telemetry AWS",
    stateId: "KA",
    district: "Bengaluru Urban",
    location: { lat: 12.9763, lng: 77.5929 },
    elevationM: 915,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.94,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "RAIN"],
  },
  {
    stationId: "AWS-KA-103",
    name: "Nandi Hills Ridge AWS",
    stateId: "KA",
    district: "Chikkaballapur",
    location: { lat: 13.3702, lng: 77.6835 },
    elevationM: 1478,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.91,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "RAIN", "SOLAR"],
  },
  {
    stationId: "AWS-KA-108",
    name: "Indiranagar Edge Node",
    stateId: "KA",
    district: "Bengaluru Urban",
    location: { lat: 12.9784, lng: 77.6408 },
    elevationM: 900,
    sensorStatus: "DEGRADED",
    sensorHealthScore: 0.41,
    lastUpdated: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    activeSensors: ["TEMP", "RAIN"],
  },
  // Goa Stations
  {
    stationId: "AWS-GA-201",
    name: "Panaji Coastal AWS",
    stateId: "GA",
    district: "North Goa",
    location: { lat: 15.4989, lng: 73.8278 },
    elevationM: 12,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.96,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "RAIN", "VISIBILITY"],
  },
  // Himachal Pradesh Stations
  {
    stationId: "AWS-HP-301",
    name: "Manali Himalayan Pass AWS",
    stateId: "HP",
    district: "Kullu",
    location: { lat: 32.2432, lng: 77.1892 },
    elevationM: 2050,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.89,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "RAIN", "VISIBILITY"],
  },
  // Kerala Stations
  {
    stationId: "AWS-KL-401",
    name: "Munnar Tea Hills AWS",
    stateId: "KL",
    district: "Idukki",
    location: { lat: 10.0889, lng: 77.0595 },
    elevationM: 1530,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.95,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "RAIN"],
  },
  // Rajasthan Stations
  {
    stationId: "AWS-RJ-501",
    name: "Udaipur Lake Observatory",
    stateId: "RJ",
    district: "Udaipur",
    location: { lat: 24.5854, lng: 73.7125 },
    elevationM: 598,
    sensorStatus: "HEALTHY",
    sensorHealthScore: 0.97,
    lastUpdated: new Date().toISOString(),
    activeSensors: ["TEMP", "HUMIDITY", "PRESSURE", "WIND", "SOLAR"],
  },
];

export const initialWeatherObservations: Record<string, WeatherObservation> = {
  "AWS-KA-101": {
    id: "OBS-KA-101-001",
    stationId: "AWS-KA-101",
    timestamp: new Date().toISOString(),
    location: { lat: 12.9716, lng: 77.5946 },
    temperature: 26.4,
    humidity: 78,
    pressure: 1012.5,
    windSpeed: 14.2,
    windDirection: 210,
    rainfall: 12.5,
    solarRadiation: 420,
    visibility: 8.5,
    cloudCover: 65,
    weatherCondition: "RAIN",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.98,
    sensorStatus: "HEALTHY",
  },
  "AWS-KA-102": {
    id: "OBS-KA-102-001",
    stationId: "AWS-KA-102",
    timestamp: new Date().toISOString(),
    location: { lat: 12.9763, lng: 77.5929 },
    temperature: 26.1,
    humidity: 80,
    pressure: 1012.3,
    windSpeed: 15.0,
    windDirection: 215,
    rainfall: 14.0,
    solarRadiation: 410,
    visibility: 8.0,
    cloudCover: 70,
    weatherCondition: "RAIN",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.94,
    sensorStatus: "HEALTHY",
  },
  "AWS-KA-103": {
    id: "OBS-KA-103-001",
    stationId: "AWS-KA-103",
    timestamp: new Date().toISOString(),
    location: { lat: 13.3702, lng: 77.6835 },
    temperature: 21.5,
    humidity: 88,
    pressure: 980.2,
    windSpeed: 28.5,
    windDirection: 190,
    rainfall: 24.2,
    solarRadiation: 280,
    visibility: 5.2,
    cloudCover: 90,
    weatherCondition: "HEAVY_STORM",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.91,
    sensorStatus: "HEALTHY",
  },
  "AWS-KA-108": {
    id: "OBS-KA-108-001",
    stationId: "AWS-KA-108",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    location: { lat: 12.9784, lng: 77.6408 },
    temperature: 48.9, // Impossible jump -> Sensor hardware fault
    humidity: 12,
    pressure: 1012.0,
    windSpeed: 0.0,
    windDirection: 0,
    rainfall: 180.0, // Extreme single-station spike vs neighbors (14mm)
    solarRadiation: 0,
    visibility: 10.0,
    cloudCover: 50,
    weatherCondition: "RAIN",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.41,
    sensorStatus: "ANOMALOUS",
  },
  "AWS-GA-201": {
    id: "OBS-GA-201-001",
    stationId: "AWS-GA-201",
    timestamp: new Date().toISOString(),
    location: { lat: 15.4989, lng: 73.8278 },
    temperature: 29.5,
    humidity: 84,
    pressure: 1009.8,
    windSpeed: 18.4,
    windDirection: 250,
    rainfall: 6.0,
    solarRadiation: 650,
    visibility: 9.0,
    cloudCover: 40,
    weatherCondition: "CLOUDY",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.96,
    sensorStatus: "HEALTHY",
  },
  "AWS-HP-301": {
    id: "OBS-HP-301-001",
    stationId: "AWS-HP-301",
    timestamp: new Date().toISOString(),
    location: { lat: 32.2432, lng: 77.1892 },
    temperature: 14.2,
    humidity: 92,
    pressure: 950.4,
    windSpeed: 38.0,
    windDirection: 310,
    rainfall: 45.0,
    solarRadiation: 150,
    visibility: 3.5,
    cloudCover: 95,
    weatherCondition: "HEAVY_STORM",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.89,
    sensorStatus: "HEALTHY",
  },
  "AWS-KL-401": {
    id: "OBS-KL-401-001",
    stationId: "AWS-KL-401",
    timestamp: new Date().toISOString(),
    location: { lat: 10.0889, lng: 77.0595 },
    temperature: 22.0,
    humidity: 86,
    pressure: 995.0,
    windSpeed: 16.5,
    windDirection: 240,
    rainfall: 18.0,
    solarRadiation: 390,
    visibility: 7.0,
    cloudCover: 80,
    weatherCondition: "RAIN",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.95,
    sensorStatus: "HEALTHY",
  },
  "AWS-RJ-501": {
    id: "OBS-RJ-501-001",
    stationId: "AWS-RJ-501",
    timestamp: new Date().toISOString(),
    location: { lat: 24.5854, lng: 73.7125 },
    temperature: 33.1,
    humidity: 45,
    pressure: 1006.2,
    windSpeed: 11.0,
    windDirection: 120,
    rainfall: 0.0,
    solarRadiation: 890,
    visibility: 10.0,
    cloudCover: 15,
    weatherCondition: "CLEAR",
    dataSource: "AWS_TELEMETRY",
    dataQualityScore: 0.97,
    sensorStatus: "HEALTHY",
  },
};
