import { AdminAccessDenied, useAdminAccess } from "@/components/AuthorityAccess";
import { SafetyNotice, SafetyShell } from "@/components/SafetyShell";
import { useSafety } from "@/contexts/SafetyContext";
import { CheckCircle2, DatabaseZap, KeyRound, ShieldCheck, UsersRound } from "lucide-react";

export default function AdminOversight() {
  const allowed = useAdminAccess();
  const { incidents, queuedIncidents, contacts, zones } = useSafety();
  if (!allowed) return <AdminAccessDenied />;
  return <SafetyShell eyebrow="Administrator workspace" title="Governance overview"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Tile icon={UsersRound} label="Role scope" value="Administrator" detail="Governance and review" /><Tile icon={DatabaseZap} label="Operational records" value={incidents.length.toString()} detail="Synchronized incidents" /><Tile icon={ShieldCheck} label="Edge queue" value={queuedIncidents.length.toString()} detail="Traveller-held pending SOS" /><Tile icon={KeyRound} label="Sensitive fields" value="Protected" detail={`${contacts.length} contacts stay local`} /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Control boundaries</p><h2 className="mt-1 text-xl font-bold text-slate-950">Administrative responsibilities</h2><div className="mt-5 space-y-3">{["Maintain role policy and privileged access review.", "Approve governed zone-data publication and synthetic-to-production model transition.", "Review tamper-evident audit commitments and retention policy.", "Monitor synchronization health without reading traveller-only pending SOS content."].map((item) => <div key={item} className="flex gap-3 rounded-xl bg-slate-50 p-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-cyan-700" /><p className="text-sm leading-5 text-slate-700">{item}</p></div>)}</div></section><section className="rounded-2xl bg-[#082235] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-300">Governed data context</p><p className="mt-2 text-3xl font-bold">{zones.length} safety zones</p><p className="mt-3 text-sm leading-6 text-slate-300">The administrator role is distinct from routine incident response. It owns policy, model, and data-governance controls; the authority role retains operational coordination.</p></section></div><SafetyNotice tone="slate"><p><strong>Prototype boundary:</strong> this separate administrator view models role separation in the local UI. Production authorization must be enforced with server-side role claims and audited policy checks on every privileged procedure.</p></SafetyNotice></SafetyShell>;
}
function Tile({ icon: Icon, label, value, detail }: { icon: React.ElementType; label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-cyan-700" /><p className="mt-4 text-xs font-bold uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
