import { AuthorityAccessDenied, useAuthorityAccess } from "@/components/AuthorityAccess";
import { RiskBadge, SafetyNotice, SafetyShell } from "@/components/SafetyShell";
import { useSafety } from "@/contexts/SafetyContext";
import { CheckCheck, CircleCheck, Clock3, RadioTower, ShieldAlert, UserRoundPlus } from "lucide-react";
import { useState } from "react";
import type { Incident, IncidentStatus } from "@/lib/safety-engine";

export default function AuthorityIncidents() {
  const allowed = useAuthorityAccess(); const { incidents, responders, transitionIncident, assignResponder, recordAudit } = useSafety(); const [filter, setFilter] = useState<"ALL" | IncidentStatus>("ALL");
  if (!allowed) return <AuthorityAccessDenied />;
  const visible = filter === "ALL" ? incidents : incidents.filter((incident) => incident.status === filter);
  return <SafetyShell eyebrow="Authority command centre" title="Incident queue"><div className="flex flex-wrap gap-2">{(["ALL", "CREATED", "VERIFIED", "ASSIGNED", "RESPONDING", "RESOLVED"] as const).map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full px-3 py-1.5 text-[11px] font-bold tracking-[.08em] ${filter === item ? "bg-[#082235] text-white" : "bg-white text-slate-600 ring-1 ring-slate-200 hover:bg-slate-50"}`}>{item}</button>)}</div><div className="mt-5 space-y-4">{visible.map((incident) => <IncidentCard key={incident.id} incident={incident} responders={responders} onTransition={transitionIncident} onAssign={assignResponder} onAudit={recordAudit} />)}</div></SafetyShell>;
}
function IncidentCard({ incident, responders, onTransition, onAssign, onAudit }: { incident: Incident; responders: ReturnType<typeof useSafety>["responders"]; onTransition: ReturnType<typeof useSafety>["transitionIncident"]; onAssign: ReturnType<typeof useSafety>["assignResponder"]; onAudit: ReturnType<typeof useSafety>["recordAudit"] }) {
  const [responderId, setResponderId] = useState(responders.find((item) => item.availability === "AVAILABLE")?.id ?? "");
  const action = incident.status === "CREATED" ? { label: "Verify incident", status: "VERIFIED" as const, icon: CheckCheck } : incident.status === "ASSIGNED" ? { label: "Start response", status: "RESPONDING" as const, icon: RadioTower } : incident.status === "RESPONDING" ? { label: "Resolve incident", status: "RESOLVED" as const, icon: CircleCheck } : undefined;
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-xs font-bold uppercase tracking-[.13em] text-slate-500">{incident.id}</p><span className="rounded-full bg-cyan-50 px-2 py-1 text-[10px] font-bold tracking-[.09em] text-cyan-800">{incident.status}</span></div><h2 className="mt-2 text-lg font-bold text-slate-950">{incident.type} · {incident.location}</h2><p className="mt-1 text-sm text-slate-600">Tourist {incident.touristId} · Opened {new Date(incident.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p></div><RiskBadge score={incident.riskScore} band={incident.severity} /></div><div className="mt-5 grid gap-3 border-y border-slate-100 py-4 sm:grid-cols-3"><Datum icon={ShieldAlert} label="Risk context" value={`${incident.riskScore}/100`} /><Datum icon={Clock3} label="Lifecycle" value={`${incident.audit.length} timestamps`} /><Datum icon={RadioTower} label="Responder" value={incident.responderName ?? "Unassigned"} /></div><div className="mt-4 flex flex-wrap items-center gap-2">{incident.status === "VERIFIED" && <><select value={responderId} onChange={(event) => setResponderId(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700"><option value="">Select responder</option>{responders.map((responder) => <option key={responder.id} value={responder.id} disabled={responder.availability !== "AVAILABLE"}>{responder.name} · {responder.eta} {responder.availability !== "AVAILABLE" ? "(busy)" : ""}</option>)}</select><button type="button" disabled={!responderId} onClick={() => onAssign(incident.id, responderId)} className="inline-flex items-center gap-2 rounded-lg bg-[#0b6177] px-3 py-2 text-xs font-bold text-white disabled:opacity-40 hover:bg-[#084b5c]"><UserRoundPlus className="h-4 w-4" />Assign responder</button></>}{action && <button type="button" onClick={() => onTransition(incident.id, action.status, action.status === "RESPONDING" ? incident.responderId ?? "UNIT-04" : "AUTH-101")} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold text-white ${action.status === "RESOLVED" ? "bg-emerald-600 hover:bg-emerald-700" : "bg-[#0b6177] hover:bg-[#084b5c]"}`}><action.icon className="h-4 w-4" />{action.label}</button>}{incident.status === "RESOLVED" && <button type="button" onClick={() => void onAudit(incident.id)} className="inline-flex items-center gap-2 rounded-lg border border-cyan-200 bg-cyan-50 px-3 py-2 text-xs font-bold text-cyan-800 hover:bg-cyan-100">Record integrity audit</button>}</div><div className="mt-5 rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">Latest audit event</p><p className="mt-1 text-sm font-semibold text-slate-700">{incident.audit[incident.audit.length - 1]?.detail}</p></div></article>;
}
function Datum({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) { return <div className="flex gap-2"><Icon className="mt-0.5 h-4 w-4 text-cyan-700" /><div><p className="text-[10px] font-bold uppercase tracking-[.11em] text-slate-500">{label}</p><p className="mt-1 text-xs font-bold text-slate-800">{value}</p></div></div>; }
