import { AuthorityAccessDenied, useAuthorityAccess } from "@/components/AuthorityAccess";
import { SafetyShell } from "@/components/SafetyShell";
import { useSafety } from "@/contexts/SafetyContext";
import { BadgeCheck, MapPinned, ShieldCheck, UsersRound } from "lucide-react";

export default function AuthorityTourists() {
  const allowed = useAuthorityAccess(); const { profile, incidents, sharingUntil, locationName } = useSafety();
  if (!allowed) return <AuthorityAccessDenied />;
  const active = incidents.filter((incident) => incident.touristId === profile.touristId && incident.status !== "RESOLVED");
  return <SafetyShell eyebrow="Authority command centre" title="Tourist register"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Active traveller profiles</p><h2 className="mt-1 text-xl font-bold text-slate-950">Authorized incident context only</h2></div><UsersRound className="h-6 w-6 text-cyan-700" /></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-slate-200 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500"><th className="pb-3">Tourist</th><th className="pb-3">Identity</th><th className="pb-3">Last known safety location</th><th className="pb-3">Active incident</th><th className="pb-3">Location sharing</th></tr></thead><tbody><tr className="border-b border-slate-100 text-sm"><td className="py-4"><p className="font-bold text-slate-900">{profile.fullName}</p><p className="mt-1 text-xs text-slate-500">{profile.touristId} · {profile.nationality}</p></td><td className="py-4"><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold tracking-[.08em] text-emerald-700"><BadgeCheck className="h-3.5 w-3.5" />{profile.verification}</span></td><td className="py-4"><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-700"><MapPinned className="h-4 w-4 text-cyan-700" />{locationName}</span></td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold tracking-[.08em] ${active.length ? "bg-rose-50 text-rose-700" : "bg-slate-100 text-slate-500"}`}>{active.length ? active[0].status : "NONE"}</span></td><td className="py-4"><span className="text-xs font-semibold text-slate-700">{sharingUntil ? "Active by explicit consent" : "Not active"}</span></td></tr></tbody></table></div></div><div className="mt-5 rounded-2xl bg-[#082235] p-5 text-white"><ShieldCheck className="h-5 w-5 text-cyan-300" /><p className="mt-4 text-sm font-bold">Privacy by design</p><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-300">This command view exposes the minimum context required for active safety coordination. In production, purpose limitation, access logs, retention controls, and explicit consent must be enforced server-side.</p></div></SafetyShell>;
}
