import { AuthorityAccessDenied, useAuthorityAccess } from "@/components/AuthorityAccess";
import { DemoSafetyMap, ZoneRiskList } from "@/components/DemoSafetyMap";
import { RiskBadge, SafetyNotice, SafetyShell } from "@/components/SafetyShell";
import { useSafety } from "@/contexts/SafetyContext";
import { BrainCircuit, ChartNoAxesCombined, CircleGauge, ShieldCheck } from "lucide-react";

export default function AuthorityRisk() {
  const allowed = useAuthorityAccess(); const { risk, zones } = useSafety();
  if (!allowed) return <AuthorityAccessDenied />;
  return <SafetyShell eyebrow="Authority command centre" title="Risk zones"><div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Spatial risk view</p><h2 className="mt-1 text-lg font-bold">Zone overlay and incident context</h2></div><DemoSafetyMap compact /></section><aside className="space-y-5"><section className="rounded-2xl bg-[#082235] p-5 text-white"><BrainCircuit className="h-5 w-5 text-cyan-300" /><p className="mt-4 text-xs font-bold uppercase tracking-[.14em] text-cyan-300">Predictive signal</p><div className="mt-1 flex items-end justify-between"><h2 className="text-xl font-bold">Current local model</h2><RiskBadge score={risk.score} band={risk.band} compact /></div><p className="mt-4 text-sm leading-6 text-slate-300">The transparent local risk model is a linear regression-inspired service built from synthetic demonstration data: history, recent activity, severity, density, hour, and historical risk.</p></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Zone score register</p><div className="mt-4"><ZoneRiskList /></div></section></aside></div><div className="mt-5 grid gap-5 lg:grid-cols-3"><Panel icon={ChartNoAxesCombined} label="Feature input" value="Recent incident count" detail="Weighted in current score calculation" /><Panel icon={CircleGauge} label="Risk expression" value="Colour-coded indicator" detail="Safe, caution, and danger bands" /><Panel icon={ShieldCheck} label="Production boundary" value="Validated data required" detail="No claims of model accuracy" /></div><SafetyNotice tone="slate"><p><strong>Model governance:</strong> a production risk engine must be trained and monitored against validated historical datasets, assessed for bias and operational value, and deployed with appropriate human oversight. The included model exists to demonstrate explainable service integration only.</p></SafetyNotice></SafetyShell>;
}
function Panel({ icon: Icon, label, value, detail }: { icon: React.ElementType; label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-cyan-700" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-slate-900">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></div>; }
