import { AuthorityAccessDenied, useAuthorityAccess } from "@/components/AuthorityAccess";
import { SafetyShell } from "@/components/SafetyShell";
import { useSafety } from "@/contexts/SafetyContext";
import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Bar, BarChart } from "recharts";
import { ChartNoAxesCombined, Clock3, ShieldAlert } from "lucide-react";

export default function AuthorityAnalytics() {
  const allowed = useAuthorityAccess(); const { incidents, zones } = useSafety();
  if (!allowed) return <AuthorityAccessDenied />;
  const severity = ["LOW", "MEDIUM", "HIGH", "CRITICAL"].map((name) => ({ name, value: incidents.filter((incident) => incident.severity === name).length }));
  const zoneData = zones.map((zone) => ({ name: zone.name.replace(" Corridor", "").replace(" Junction", ""), risk: zone.score, incidents: zone.incidentCount }));
  const active = incidents.filter((incident) => incident.status !== "RESOLVED").length; const resolved = incidents.length - active;
  return <SafetyShell eyebrow="Authority command centre" title="Analytics"><div className="grid gap-4 sm:grid-cols-3"><Card icon={ShieldAlert} label="Active vs resolved" value={`${active} / ${resolved}`} detail="Current local incident register" /><Card icon={Clock3} label="Average response" value="11 min" detail="Synthetic demonstration calculation" /><Card icon={ChartNoAxesCombined} label="High-risk locations" value={zones.filter((zone) => zone.score >= 70).length.toString()} detail="Based on current zone model" /></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="h-[360px] rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Risk score and incident history</p><h2 className="mt-1 text-lg font-bold text-slate-950">Zone comparison</h2><div className="mt-4 h-[270px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={zoneData} margin={{ top: 5, right: 5, left: -15, bottom: 5 }}><XAxis dataKey="name" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="risk" name="Risk score" fill="#0e7490" radius={[5, 5, 0, 0]} /><Bar dataKey="incidents" name="Incident count" fill="#f59e0b" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="h-[360px] rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Incident distribution</p><h2 className="mt-1 text-lg font-bold text-slate-950">Severity classes</h2><div className="mt-4 h-[270px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={severity} dataKey="value" nameKey="name" innerRadius={62} outerRadius={94} paddingAngle={4}>{severity.map((entry, index) => <Cell key={entry.name} fill={["#10b981", "#f59e0b", "#f43f5e", "#9f1239"][index]} />)}</Pie><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /></PieChart></ResponsiveContainer></div></section></div><p className="mt-5 text-xs leading-5 text-slate-500">All current analytics are derived from prototype incident and zone data. They are clearly visualized for workflow demonstration and should not be interpreted as real-world safety statistics.</p></SafetyShell>;
}
function Card({ icon: Icon, label, value, detail }: { icon: React.ElementType; label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-cyan-700" /><p className="mt-4 text-xs font-bold uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>; }
